type BatchTopic = { slug: string; title: string; excerpt: string; focus: string; tasks: string[]; checks: string[] };

const topics: BatchTopic[] = [
  ['philippines-operations-support-sop-handoff', 'Philippines operations support SOP handoff guide', 'Turn recurring operations work into a clear handoff for a Philippines-based support role.', 'SOP handoffs', ['record the current process', 'name the review owner', 'log exceptions'], ['Can a new person follow the example?', 'Who approves exceptions?', 'Where is the current SOP stored?']],
  ['philippines-virtual-assistant-calendar-management', 'Philippines virtual assistant calendar management checklist', 'Set safe rules for scheduling, rescheduling, meeting notes, and calendar privacy.', 'calendar management', ['calendar triage', 'meeting preparation', 'follow-up drafts'], ['Which meetings need approval?', 'What can be moved?', 'Who sees private events?']],
  ['philippines-customer-support-ticket-triage', 'Philippines customer support ticket triage workflow', 'Build a practical ticket queue with tags, approved first replies, and escalation rules.', 'ticket triage', ['tag incoming tickets', 'send approved first replies', 'flag urgent cases'], ['Which tags are required?', 'What counts as urgent?', 'Who owns an exception?']],
  ['philippines-outsourced-inbox-management', 'Philippines outsourced inbox management playbook', 'Create an inbox lane that sorts messages, drafts replies, and protects sensitive decisions.', 'inbox management', ['sort by urgency', 'draft routine replies', 'maintain a follow-up list'], ['Which messages stay private?', 'What may be sent?', 'How are overdue replies flagged?']],
  ['philippines-remote-team-daily-reporting', 'Philippines remote team daily reporting routine', 'Use a short daily report to show completed work, blockers, and the next handoff.', 'daily reporting', ['update the work board', 'link completed work', 'record blockers'], ['What must every report include?', 'Who reads it?', 'When does a blocker escalate?']],
  ['philippines-outsourced-lead-research-process', 'Philippines outsourced lead research process', 'Plan a research role around defined sources, evidence links, and manager review.', 'lead research', ['find prospects from approved sources', 'capture evidence', 'remove duplicates'], ['What makes a prospect fit?', 'Which sources are allowed?', 'Who approves outreach?']],
  ['philippines-virtual-assistant-crm-cleanup', 'Philippines virtual assistant CRM cleanup checklist', 'Keep CRM records useful with field rules, duplicate checks, and a review queue.', 'CRM cleanup', ['standardize fields', 'merge obvious duplicates', 'flag uncertain records'], ['Which fields are required?', 'What cannot be merged?', 'Who reviews uncertain changes?']],
  ['philippines-outsourced-bookkeeping-support-controls', 'Philippines outsourced bookkeeping support controls', 'Separate bookkeeping preparation from approvals, payments, and financial decisions.', 'bookkeeping support', ['collect source documents', 'reconcile approved records', 'prepare a review list'], ['Who approves entries?', 'Which changes need evidence?', 'Who releases payments?']],
  ['philippines-remote-staff-onboarding-week-one', 'Philippines remote staff first-week onboarding plan', 'Give a new Philippines-based team member a narrow first week with examples and daily feedback.', 'first-week onboarding', ['review the role brief', 'complete sample tasks', 'close the week with a scorecard'], ['Are examples ready?', 'Who checks the first work?', 'What access is still needed?']],
  ['philippines-outsourced-content-calendar-workflow', 'Philippines outsourced content calendar workflow', 'Coordinate briefs, drafts, reviews, and publishing dates without losing ownership.', 'content calendars', ['maintain the calendar', 'check brief completeness', 'prepare review reminders'], ['Who owns final approval?', 'What makes a brief ready?', 'Which dates are locked?']],
  ['philippines-virtual-assistant-meeting-notes', 'Philippines virtual assistant meeting notes workflow', 'Turn meetings into accurate notes, assigned actions, and a visible follow-up list.', 'meeting notes', ['capture decisions', 'assign action owners', 'send a draft recap'], ['What is a decision?', 'Who receives the recap?', 'What requires manager approval?']],
  ['philippines-outsourced-ecommerce-order-support', 'Philippines outsourced ecommerce order support checklist', 'Handle order-status questions with approved replies and clear refund escalation.', 'order support', ['check order status', 'send approved updates', 'escalate refund requests'], ['Which systems are read-only?', 'What is the refund threshold?', 'Who handles complaints?']],
  ['philippines-remote-team-quality-assurance-scorecard', 'Philippines remote team quality assurance scorecard', 'Use a small scorecard to review accuracy, completeness, timeliness, and blockers.', 'quality assurance', ['sample completed work', 'score against examples', 'record corrective coaching'], ['What is a pass?', 'How large is the sample?', 'Who owns repeated misses?']],
  ['philippines-outsourced-vendor-follow-up', 'Philippines outsourced vendor follow-up process', 'Keep vendor requests moving with a tracker, approved messages, and escalation dates.', 'vendor follow-up', ['maintain the tracker', 'send approved reminders', 'flag missed commitments'], ['Which vendors may be contacted?', 'What can be promised?', 'When does the owner step in?']],
  ['philippines-virtual-assistant-file-organization', 'Philippines virtual assistant file organization guide', 'Organize shared files with naming rules, source links, and a reviewable archive.', 'file organization', ['apply naming rules', 'move files to approved folders', 'record uncertain items'], ['Who owns folder access?', 'What must not be moved?', 'How are duplicates handled?']],
  ['philippines-outsourced-social-media-assistance', 'Philippines outsourced social media assistance checklist', 'Define safe research, scheduling, and reporting tasks while keeping publishing approval clear.', 'social media assistance', ['prepare the content queue', 'check links and assets', 'prepare weekly metrics'], ['Who approves copy?', 'Which replies are escalated?', 'What account access is needed?']],
  ['philippines-remote-staff-password-access-review', 'Philippines remote staff password and access review', 'Review named accounts and least-privilege access before expanding a remote role.', 'access review', ['list required accounts', 'remove unused access', 'record the next review date'], ['Who owns each account?', 'Is MFA enabled?', 'How quickly can access be removed?']],
  ['philippines-outsourced-recruiting-coordinator-workflow', 'Philippines outsourced recruiting coordinator workflow', 'Structure candidate scheduling, document collection, and status updates around hiring-manager decisions.', 'recruiting coordination', ['schedule interviews', 'maintain candidate status', 'prepare interview packets'], ['Who makes the hiring decision?', 'Which data is sensitive?', 'What needs approval before sending?']],
  ['philippines-virtual-assistant-project-tracker', 'Philippines virtual assistant project tracker setup', 'Create a simple tracker that makes owners, due dates, blockers, and next actions visible.', 'project tracking', ['update task status', 'check due dates', 'summarize blockers'], ['What counts as done?', 'Who changes priorities?', 'Which blockers are urgent?']],
  ['philippines-outsourced-data-entry-quality-checks', 'Philippines outsourced data entry quality checks', 'Reduce rework with source documents, field rules, sampling, and a correction log.', 'data entry', ['enter approved records', 'run field checks', 'log corrections'], ['What is the source of truth?', 'Which fields are mandatory?', 'Who approves a new pattern?']],
  ['philippines-remote-customer-success-follow-up', 'Philippines remote customer success follow-up routine', 'Keep customer follow-ups consistent with approved templates, dates, and escalation notes.', 'customer success follow-up', ['update the follow-up queue', 'draft check-in messages', 'flag risk signals'], ['Which messages need approval?', 'What is a risk signal?', 'Who owns a dissatisfied customer?']],
  ['philippines-outsourced-marketing-reporting', 'Philippines outsourced marketing reporting checklist', 'Prepare source-linked marketing reports that managers can review quickly.', 'marketing reporting', ['collect approved metrics', 'check source dates', 'prepare a weekly summary'], ['Which metrics matter?', 'What is the reporting period?', 'Who approves the interpretation?']],
  ['philippines-outsourced-operations-weekly-review', 'Philippines outsourced operations weekly review agenda', 'Run a short weekly review that turns completed work, corrections, and blockers into next actions.', 'weekly operations reviews', ['collect the done-list', 'sample completed work', 'assign next actions'], ['Which work is complete?', 'What needs correction?', 'Who owns each next action?']],
  ['philippines-virtual-assistant-travel-planning', 'Philippines virtual assistant travel planning workflow', 'Coordinate research, draft itineraries, and booking details while keeping final travel decisions with the owner.', 'travel planning', ['collect preferences', 'compare approved options', 'prepare a review-ready itinerary'], ['Which details are confirmed?', 'Who approves the itinerary?', 'Which purchases require owner action?']],
  ['philippines-outsourced-sales-admin-follow-up', 'Philippines outsourced sales admin follow-up process', 'Keep sales follow-up organized with dated tasks, approved drafts, and clear handoffs to the sales owner.', 'sales administration', ['update opportunity tasks', 'draft approved follow-ups', 'flag stalled opportunities'], ['What is the next action?', 'Which message needs approval?', 'When does the owner take over?']],
  ['philippines-remote-team-shift-handoff', 'Philippines remote team shift handoff checklist', 'Make work visible across time zones with a compact handoff covering status, evidence, and exceptions.', 'shift handoffs', ['update task status', 'link supporting files', 'write exception notes'], ['What changed this shift?', 'What must happen next?', 'Who owns the exception?']],
  ['philippines-outsourced-invoice-processing-workflow', 'Philippines outsourced invoice processing workflow', 'Prepare invoice records for review with source checks, duplicate detection, and approval boundaries.', 'invoice processing', ['collect approved invoices', 'match records to sources', 'prepare an exception queue'], ['Who approves payment?', 'What proves a match?', 'How are duplicates held?']],
  ['philippines-virtual-assistant-research-brief', 'Philippines virtual assistant research brief template', 'Turn a broad question into a source-led research brief with scope, evidence, and a clear manager decision.', 'research briefs', ['define the question', 'collect source links', 'summarize open questions'], ['What is in scope?', 'Which sources are authoritative?', 'What decision will the brief support?']],
  ['philippines-outsourced-website-content-qa', 'Philippines outsourced website content QA checklist', 'Review page content for links, metadata, consistency, and approval status before publication.', 'website content QA', ['check page fields', 'test links', 'record approval status'], ['Which page is the source of truth?', 'What fails publication?', 'Who gives final approval?']],
  ['philippines-remote-staff-device-onboarding', 'Philippines remote staff device onboarding checklist', 'Prepare a safe device handoff with named ownership, required tools, and a documented recovery path.', 'device onboarding', ['record device assignment', 'install approved tools', 'confirm recovery steps'], ['Who owns the device?', 'Which software is required?', 'How is the device recovered?']],
  ['philippines-outsourced-community-moderation', 'Philippines outsourced community moderation workflow', 'Give a moderator clear queues, response rules, evidence capture, and escalation for risky conversations.', 'community moderation', ['review the queue', 'apply approved labels', 'escalate policy exceptions'], ['What violates the policy?', 'Which replies are approved?', 'Who handles threats or urgent risk?']],
  ['philippines-virtual-assistant-podcast-production', 'Philippines virtual assistant podcast production checklist', 'Coordinate episode assets, show notes, publishing tasks, and review dates without owning editorial approval.', 'podcast production', ['collect approved assets', 'prepare show notes', 'track publishing tasks'], ['Who approves the final copy?', 'Which files are final?', 'What is the release date?']],
  ['philippines-outsourced-market-research-tracker', 'Philippines outsourced market research tracker', 'Maintain a source-linked research tracker that separates evidence collection from business conclusions.', 'market research tracking', ['record approved sources', 'remove duplicate entries', 'flag uncertain findings'], ['What counts as evidence?', 'Which fields are required?', 'Who reviews conclusions?']],
  ['philippines-remote-team-okr-update-routine', 'Philippines remote team OKR update routine', 'Collect concise progress updates with links, confidence notes, and manager-owned decisions.', 'OKR updates', ['request status updates', 'link evidence', 'summarize blockers'], ['What is the evidence?', 'Who changes the objective?', 'When is a risk escalated?']],
  ['philippines-outsourced-help-center-maintenance', 'Philippines outsourced help center maintenance guide', 'Keep help content accurate with a review queue, source owners, and a controlled update process.', 'help center maintenance', ['find stale pages', 'check source changes', 'prepare update drafts'], ['Who owns the answer?', 'What requires subject review?', 'When is a page archived?']],
  ['philippines-virtual-assistant-event-coordination', 'Philippines virtual assistant event coordination workflow', 'Organize event tasks, guest information, reminders, and follow-up drafts around a named event owner.', 'event coordination', ['maintain the event tracker', 'prepare approved reminders', 'record attendance notes'], ['Which details are sensitive?', 'Who approves invitations?', 'What is the follow-up owner?']],
  ['philippines-outsourced-purchase-order-support', 'Philippines outsourced purchase order support checklist', 'Prepare purchase order records and exception notes while leaving vendor approval and commitments with the manager.', 'purchase order support', ['collect request details', 'check required fields', 'prepare approval notes'], ['Who approves the order?', 'What fields are mandatory?', 'What cannot be promised?']],
  ['philippines-remote-team-performance-coaching-notes', 'Philippines remote team performance coaching notes', 'Keep coaching notes factual, dated, and useful for a manager without turning routine support into a personnel decision.', 'coaching notes', ['record observed examples', 'link agreed actions', 'schedule the next review'], ['What is directly observed?', 'Who owns the decision?', 'Where are sensitive notes stored?']],
  ['philippines-outsourced-knowledge-base-indexing', 'Philippines outsourced knowledge base indexing workflow', 'Make internal knowledge easier to use by tagging articles, checking owners, and logging gaps.', 'knowledge base indexing', ['apply agreed tags', 'check article owners', 'log missing guidance'], ['Which taxonomy is current?', 'Who approves new tags?', 'How are gaps escalated?']],
  ['philippines-virtual-assistant-client-report-preparation', 'Philippines virtual assistant client report preparation', 'Assemble client report inputs with source links, date ranges, and a manager review before delivery.', 'client report preparation', ['collect approved metrics', 'check reporting periods', 'prepare a review draft'], ['Which numbers are approved?', 'Who interprets the result?', 'When is the report due?']],
  ['philippines-outsourced-workflow-documentation-audit', 'Philippines outsourced workflow documentation audit', 'Audit recurring process documents for owners, examples, access limits, and exception paths.', 'workflow documentation audits', ['list active SOPs', 'check examples and owners', 'record missing controls'], ['Which document is current?', 'Who approves changes?', 'What exception path is missing?']],
  ['philippines-operations-support-daily-priorities', 'Philippines operations support daily priorities checklist', 'Turn a busy operations queue into a short, reviewable priority list with clear ownership.', 'daily priorities', ['sort the queue', 'confirm due dates', 'flag blocked work'], ['Which task is first?', 'Who can change priority?', 'What evidence shows progress?']],
  ['philippines-virtual-assistant-inbox-escalation', 'Philippines virtual assistant inbox escalation rules', 'Set practical boundaries for sorting messages, drafting replies, and escalating sensitive requests.', 'inbox escalation', ['label incoming mail', 'draft routine replies', 'route sensitive requests'], ['Which messages need approval?', 'What is urgent?', 'Who owns the response?']],
  ['philippines-outsourced-customer-support-macro-review', 'Philippines outsourced customer support macro review', 'Keep customer reply templates accurate with an owner, sample checks, and a change log.', 'support macro review', ['list active macros', 'test sample replies', 'record requested changes'], ['Who approves wording?', 'Which cases need a custom reply?', 'When is a macro retired?']],
  ['philippines-remote-team-work-queue-aging', 'Philippines remote team work queue aging review', 'Find aging tasks before they become missed commitments by using dates, owners, and escalation notes.', 'queue aging', ['sort by age', 'check the latest handoff', 'escalate overdue work'], ['What counts as overdue?', 'Who owns the next step?', 'Where is the blocker recorded?']],
  ['philippines-outsourced-calendar-conflict-review', 'Philippines outsourced calendar conflict review', 'Resolve scheduling conflicts with stated priorities, approval rules, and a visible decision log.', 'calendar conflicts', ['find overlapping meetings', 'check meeting priority', 'prepare proposed changes'], ['Which meeting wins?', 'Who approves a move?', 'What stays private?']],
  ['philippines-virtual-assistant-document-formatting', 'Philippines virtual assistant document formatting workflow', 'Create a bounded document formatting lane with templates, quality checks, and final-owner approval.', 'document formatting', ['apply the approved template', 'check headings and links', 'prepare a review copy'], ['Which template is current?', 'What content is out of scope?', 'Who approves the final file?']],
  ['philippines-outsourced-crm-lead-routing', 'Philippines outsourced CRM lead routing checklist', 'Route new leads using agreed fields, duplicate checks, and a clear handoff to the sales owner.', 'lead routing', ['check required fields', 'remove duplicate records', 'assign the next task'], ['What makes a lead ready?', 'Which owner receives it?', 'When is a record held?']],
  ['philippines-remote-staff-weekly-one-on-one-prep', 'Philippines remote staff weekly one-on-one preparation', 'Prepare a concise one-on-one agenda from completed work, open questions, and agreed follow-ups.', 'one-on-one preparation', ['collect updates', 'summarize blockers', 'draft follow-up actions'], ['Which topics are factual?', 'Who makes people decisions?', 'Where are private notes stored?']],
  ['philippines-outsourced-project-status-summary', 'Philippines outsourced project status summary template', 'Give project owners a consistent status summary with milestones, risks, evidence, and next actions.', 'project status summaries', ['check milestone updates', 'link supporting work', 'summarize risks'], ['What is actually complete?', 'Who owns each risk?', 'Which decision is pending?']],
  ['philippines-virtual-assistant-spreadsheet-cleanup', 'Philippines virtual assistant spreadsheet cleanup checklist', 'Improve spreadsheet usability with agreed field rules, source checks, and a correction queue.', 'spreadsheet cleanup', ['standardize fields', 'check formulas and dates', 'log uncertain changes'], ['What is the source of truth?', 'Which formulas are protected?', 'Who approves a new rule?']],
  ['philippines-outsourced-appointment-confirmation', 'Philippines outsourced appointment confirmation workflow', 'Coordinate confirmations and reminders with approved messages, privacy limits, and exception handling.', 'appointment confirmations', ['check the appointment list', 'send approved reminders', 'flag changes'], ['Which details may be shared?', 'Who handles cancellations?', 'What needs owner approval?']],
  ['philippines-remote-team-blocker-log', 'Philippines remote team blocker log guide', 'Make blockers actionable by recording impact, evidence, owner, and the next unblock step.', 'blocker logging', ['record the blocker', 'attach evidence', 'set the next review time'], ['What makes a blocker urgent?', 'Who can unblock it?', 'When is it escalated?']],
  ['philippines-outsourced-competitor-research-workflow', 'Philippines outsourced competitor research workflow', 'Collect approved competitor evidence without confusing source facts with business conclusions.', 'competitor research', ['define the comparison', 'capture source links', 'flag uncertain findings'], ['Which sources are allowed?', 'What is directly observed?', 'Who reviews conclusions?']],
  ['philippines-virtual-assistant-quote-request-coordination', 'Philippines virtual assistant quote request coordination', 'Organize quote requests and supplier replies while leaving selection and commitments with the business owner.', 'quote coordination', ['collect request details', 'track supplier replies', 'prepare a comparison'], ['Who chooses the supplier?', 'What can be promised?', 'Which details are confidential?']],
  ['philippines-outsourced-returns-support-process', 'Philippines outsourced returns support process', 'Handle returns information with approved replies, order checks, and clear refund escalation.', 'returns support', ['check order details', 'send approved instructions', 'prepare an exception note'], ['Which policy applies?', 'Who approves a refund?', 'What evidence is required?']],
  ['philippines-remote-staff-access-offboarding', 'Philippines remote staff access offboarding checklist', 'Close a remote role safely with a named owner, account list, evidence, and handoff confirmation.', 'access offboarding', ['list active accounts', 'remove approved access', 'record confirmation'], ['Who owns removal?', 'What data must be returned?', 'How is completion evidenced?']],
  ['philippines-outsourced-sop-version-control', 'Philippines outsourced SOP version control guide', 'Keep operating procedures usable by naming owners, versions, examples, and change approvals.', 'SOP version control', ['check the current version', 'record requested edits', 'archive superseded copies'], ['Which copy is current?', 'Who approves edits?', 'Where are old versions stored?']],
  ['philippines-virtual-assistant-feedback-tracker', 'Philippines virtual assistant feedback tracker setup', 'Turn review comments into a small correction tracker with examples, owners, and due dates.', 'feedback tracking', ['capture the correction', 'link the example', 'check the next sample'], ['What is the actual error?', 'Who owns the correction?', 'When is the fix verified?']],
  ['philippines-outsourced-client-onboarding-coordination', 'Philippines outsourced client onboarding coordination checklist', 'Coordinate onboarding tasks and documents while keeping scope, approvals, and commitments with the account owner.', 'client onboarding', ['maintain the checklist', 'request approved documents', 'flag missing items'], ['Which documents are required?', 'Who approves scope?', 'What cannot be promised?']],
  ['philippines-remote-team-month-end-admin-close', 'Philippines remote team month-end admin close', 'Prepare month-end administrative records with source checks, missing-item flags, and manager review.', 'month-end administration', ['collect approved records', 'check missing fields', 'prepare an exception list'], ['What is the close date?', 'Who approves changes?', 'Which items remain open?']],
  ['philippines-outsourced-service-request-intake', 'Philippines outsourced service request intake workflow', 'Turn incoming requests into complete, routed work items with scope, owner, due date, and approval status.', 'service request intake', ['capture request details', 'check required fields', 'route to the owner'], ['What is in scope?', 'Who approves the request?', 'When should it be escalated?']],
  ['philippines-virtual-assistant-knowledge-transfer', 'Philippines virtual assistant knowledge transfer checklist', 'Capture repeatable work, examples, and open questions before a task changes hands.', 'knowledge transfer', ['record the process', 'attach finished examples', 'review open questions'], ['Which steps are essential?', 'Who confirms the handoff?', 'What remains unresolved?']],
].map((row) => {
  const [slug, title, excerpt, focus, tasks, checks] = row as [string, string, string, string, string[], string[]];
  return { slug, title, excerpt, focus, tasks, checks };
});

export const aug10BlogDates: Record<string, string> = {
  'philippines-operations-support-daily-priorities': '2026-08-10',
  'philippines-virtual-assistant-inbox-escalation': '2026-08-10',
  'philippines-outsourced-customer-support-macro-review': '2026-08-10',
  'philippines-remote-team-work-queue-aging': '2026-08-10',
  'philippines-outsourced-calendar-conflict-review': '2026-08-10',
  'philippines-virtual-assistant-document-formatting': '2026-08-10',
  'philippines-outsourced-crm-lead-routing': '2026-08-10',
  'philippines-remote-staff-weekly-one-on-one-prep': '2026-08-10',
  'philippines-outsourced-project-status-summary': '2026-08-10',
  'philippines-virtual-assistant-spreadsheet-cleanup': '2026-08-10',
  'philippines-outsourced-appointment-confirmation': '2026-08-10',
  'philippines-remote-team-blocker-log': '2026-08-10',
  'philippines-outsourced-competitor-research-workflow': '2026-08-10',
  'philippines-virtual-assistant-quote-request-coordination': '2026-08-10',
  'philippines-outsourced-returns-support-process': '2026-08-10',
  'philippines-remote-staff-access-offboarding': '2026-08-10',
  'philippines-outsourced-sop-version-control': '2026-08-10',
  'philippines-virtual-assistant-feedback-tracker': '2026-08-10',
  'philippines-outsourced-client-onboarding-coordination': '2026-08-10',
  'philippines-remote-team-month-end-admin-close': '2026-08-10',
  'philippines-outsourced-service-request-intake': '2026-08-10',
  'philippines-virtual-assistant-knowledge-transfer': '2026-08-10',
};

// August 11, 2026 campaign records. Each article owns its literal publication
// date here; do not replace these bindings with a shared campaign constant.
export const aug11BlogPosts = [
  { slug: 'philippines-outsourced-admin-backlog-reduction', title: 'Philippines outsourced admin backlog reduction plan', excerpt: 'Reduce a growing admin backlog with clear intake, aging rules, and a practical review lane.', minutes: 11, publishedAt: '2026-08-11' },
  { slug: 'philippines-virtual-assistant-contact-list-maintenance', title: 'Philippines virtual assistant contact list maintenance guide', excerpt: 'Keep contact records dependable with field ownership, source checks, and a safe correction queue.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-client-follow-up-tracker', title: 'Philippines outsourced client follow-up tracker', excerpt: 'Give client follow-up a visible home with next actions, due dates, and manager-owned exceptions.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-remote-team-weekly-planning', title: 'Philippines remote team weekly planning checklist', excerpt: 'Start each week with a realistic work plan, ownership notes, and a short list of unresolved decisions.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-document-request-tracking', title: 'Philippines outsourced document request tracking workflow', excerpt: 'Track requested documents without losing source context, due dates, or privacy boundaries.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-virtual-assistant-presentation-preparation', title: 'Philippines virtual assistant presentation preparation checklist', excerpt: 'Prepare presentation files with approved content, consistent formatting, and a clear final review.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-customer-feedback-categorization', title: 'Philippines outsourced customer feedback categorization guide', excerpt: 'Turn customer comments into consistent categories while keeping interpretation with the business owner.', minutes: 11, publishedAt: '2026-08-11' },
  { slug: 'philippines-remote-staff-time-off-coordination', title: 'Philippines remote staff time-off coordination workflow', excerpt: 'Coordinate time-off requests with coverage notes, approval boundaries, and an accurate team calendar.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-sales-data-hygiene', title: 'Philippines outsourced sales data hygiene checklist', excerpt: 'Keep sales records usable with required fields, evidence links, and a review path for uncertain changes.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-virtual-assistant-survey-response-review', title: 'Philippines virtual assistant survey response review', excerpt: 'Prepare survey response summaries with transparent categories, source counts, and open questions.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-appointment-rescheduling', title: 'Philippines outsourced appointment rescheduling process', excerpt: 'Handle rescheduling requests with approved options, calendar checks, and a clear owner for exceptions.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-remote-team-holiday-coverage-plan', title: 'Philippines remote team holiday coverage plan', excerpt: 'Prepare holiday coverage with named backups, priority work, and a documented escalation route.', minutes: 11, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-product-catalog-updates', title: 'Philippines outsourced product catalog update workflow', excerpt: 'Update product catalog records from approved sources while protecting descriptions, media, and restricted fields.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-virtual-assistant-webinar-coordination', title: 'Philippines virtual assistant webinar coordination checklist', excerpt: 'Coordinate webinar guests, reminders, assets, and follow-up drafts around one event owner.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-document-review-queue', title: 'Philippines outsourced document review queue', excerpt: 'Create a review queue that separates completeness checks from legal, financial, or policy decisions.', minutes: 11, publishedAt: '2026-08-11' },
  { slug: 'philippines-remote-team-status-meeting-prep', title: 'Philippines remote team status meeting preparation', excerpt: 'Prepare a focused status meeting from milestones, blockers, evidence, and decisions still waiting on an owner.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-order-entry-controls', title: 'Philippines outsourced order entry controls', excerpt: 'Enter approved orders accurately with source matching, required fields, and a hold process for exceptions.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-virtual-assistant-email-template-library', title: 'Philippines virtual assistant email template library guide', excerpt: 'Maintain useful email templates with approved language, ownership, examples, and retirement rules.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-research-source-checking', title: 'Philippines outsourced research source-checking workflow', excerpt: 'Make research handoffs easier to trust by recording source dates, links, scope, and unresolved conflicts.', minutes: 11, publishedAt: '2026-08-11' },
  { slug: 'philippines-remote-staff-work-sample-review', title: 'Philippines remote staff work-sample review guide', excerpt: 'Review early work samples against concrete examples before expanding a Philippines-based role.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-outsourced-recurring-task-calendar', title: 'Philippines outsourced recurring task calendar', excerpt: 'Turn recurring business tasks into a calendar with owners, evidence, review dates, and exception notes.', minutes: 10, publishedAt: '2026-08-11' },
  { slug: 'philippines-virtual-assistant-client-intake-notes', title: 'Philippines virtual assistant client intake notes', excerpt: 'Capture client intake details consistently while keeping scope, commitments, and sensitive decisions with the owner.', minutes: 10, publishedAt: '2026-08-11' },
] as const;

const aug11BlogBasics = Object.fromEntries(aug11BlogPosts.map((post) => [post.slug, {
  intro: `A dependable ${post.title.replace(/^Philippines (outsourced|virtual assistant|remote team|remote staff) /i, '').replace(/ guide| checklist| workflow| process| plan| setup| queue| calendar$/i, '')} lane starts with clear inputs, a named reviewer, and an exception path. Keep the Philippines-based role focused on preparation and follow-through while the business owner keeps consequential decisions.`,
  sections: [
    { title: 'Define the work lane', paragraphs: [`Write down the request or record that starts this work, the fields that must be present, and the finished example a reviewer will use. Keep the first handoff narrow enough to check in one sitting.`, 'Separate information gathering and preparation from approvals, commitments, payments, policy decisions, and changes that affect a customer or employee. The role can flag an issue and prepare a draft for the owner.'], checks: ['What starts the task?', 'Which fields or documents are required?', 'What does a finished example look like?'] },
    { title: 'Make ownership visible', paragraphs: ['Use one source-of-truth list with an owner, due date, current status, and link to supporting evidence. Record a short note when an item is blocked instead of leaving the next person to guess.', 'Give access only to the systems needed for this lane. Use named accounts and a clear owner for changes or removal.'], checks: ['Who reviews the work?', 'Where is supporting evidence stored?', 'What happens when information is missing?'] },
    { title: 'Review and improve', paragraphs: ['Sample the first completed items against the same checklist. Turn repeated corrections into an example or a short instruction, and keep unusual cases in an exception list for the manager.', 'After the first review cycle, decide whether the lane is ready for normal oversight, needs a narrower scope, or needs a new approval rule.'], checks: ['Which errors recur?', 'Who decides an exception?', 'What evidence supports expanding the role?'] },
  ],
}])) as Record<string, { intro: string; sections: { title: string; paragraphs: string[]; checks: string[] }[] }>;

export const dailyBlogPosts = topics.map(({ slug, title, excerpt }) => ({
  slug,
  title,
  excerpt,
  minutes: 10,
  publishedAt: aug10BlogDates[slug],
}));

export const allDailyBlogPosts = [...dailyBlogPosts, ...aug11BlogPosts];

export const dailyBlogBasics = Object.fromEntries(topics.map(({ slug, focus, tasks, checks }) => [slug, {
  intro: `A useful ${focus} role starts with a small, visible task lane. Give the Philippines-based team member examples, a named reviewer, and written limits before adding more work.`,
  sections: [
    { title: 'Define the starting lane', paragraphs: [`List the first tasks in order and attach one finished example to each. The starting lane should be repeatable and easy for a manager to check. Begin with ${tasks[0]}, then add the next task only after the first output is steady.`, 'Keep decisions about money, pricing, legal matters, hiring, and policy exceptions with your manager. The role can collect facts and prepare a draft, but the owner should approve consequential changes.'], checks },
    { title: 'Set the handoff and review', paragraphs: ['Use one task board, one source-of-truth folder, and one short daily note. The worker should link completed work and record any item that cannot be finished. Review the first five examples against the same checklist.', 'Add exactly the access required for the starting tasks. Use named accounts, multi-factor authentication where available, and a removal owner. Review permissions before expanding the role.'], checks: [...checks, 'Who removes access when the work ends?'] },
    { title: 'Improve after the first week', paragraphs: ['At the end of the first week, compare accuracy, completeness, timeliness, and open questions. Turn repeated corrections into a short SOP or example. This keeps the role useful without making the brief vague.', 'Keep a decision log for exceptions and update the review owner when responsibility changes. A clear escalation path protects both the business and the Philippines-based worker.'], checks: [...checks, 'What evidence supports adding another task?'] },
  ],
}]));

export const allDailyBlogBasics = { ...dailyBlogBasics, ...aug11BlogBasics };
