type BatchTopic = { slug: string; title: string; excerpt: string; focus: string; tasks: string[]; checks: string[] };

const topics: BatchTopic[] = [
  ['philippines-operations-support-sop-handoff', 'Philippines operations support SOP handoff guide', 'Turn recurring operations work into a clear handoff for a Philippines-based support role.', 'SOP handoffs', ['record the current process', 'name the review owner', 'log exceptions'], ['Can a new person follow the example?', 'Who approves exceptions?', 'Where is the current SOP stored?']],
  ['philippines-virtual-assistant-calendar-management', 'Philippines virtual assistant calendar management checklist', 'Set safe rules for scheduling, rescheduling, meeting notes, and calendar privacy.', 'calendar management', ['calendar triage', 'meeting preparation', 'follow-up drafts'], ['Which meetings need approval?', 'What can be moved?', 'Who sees private events?']],
  ['philippines-customer-support-ticket-triage', 'Philippines customer support ticket triage workflow', 'Build a practical ticket queue with tags, approved first replies, and escalation rules.', 'ticket triage', ['tag incoming tickets', 'send approved first replies', 'flag urgent cases'], ['Which tags are required?', 'What counts as urgent?', 'Who owns an exception?']],
  ['philippines-outsourced-inbox-management', 'Philippines outsourced inbox management playbook', 'Create an inbox lane that sorts messages, drafts replies, and protects sensitive decisions.', 'inbox management', ['sort by urgency', 'draft routine replies', 'maintain a follow-up list'], ['Which messages stay private?', 'What may be sent?', 'How are overdue replies flagged?']],
  ['philippines-remote-team-daily-reporting', 'Philippines remote team daily reporting routine', 'Use a short daily report to show completed work, blockers, and the next handoff.', 'daily reporting', ['update the work board', 'link completed work', 'record blockers'], ['What must every report include?', 'Who reads it?', 'When does a blocker escalate?']],
  ['philippines-outsourced-lead-research-process', 'Philippines outsourced lead research process', 'Plan a research role around defined sources, evidence links, and manager review.', 'lead research', ['find prospects from approved sources', 'capture evidence', 'remove duplicates'], ['What makes a prospect fit?', 'Which sources are allowed?', 'Who approves outreach?']],
  ['philippines-virtual-assistant-crm-cleanup', 'Philippines virtual assistant CRM cleanup checklist', 'Keep CRM records useful with field rules, duplicate checks, and a review queue.', 'CRM cleanup', ['standardize fields', 'merge obvious duplicates', 'flag uncertain records'], ['Which fields are required?', 'What cannot be merged?', 'Who reviews uncertain changes?']],
  ['philippines-outsourced-bookkeeping-support-controls', 'Philippines outsourced bookkeeping support controls', 'Separate bookkeeping preparation from approvals, payments, and financial decisions.', 'bookkeeping support', ['collect source documents', 'reconcile approved records', 'prepare a review list'], ['Who approves entries?', 'Which changes need evidence?', 'Who releases payments?']],
  ['philippines-remote-staff-onboarding-week-one', 'Philippines remote staff first-week onboarding plan', 'Give a new Philippines-based team member a narrow first week with examples and daily feedback.', 'first-week onboarding', ['review the role brief', 'complete sample tasks', 'close the week with a scorecard'], ['Are examples ready?', 'Who checks the first work?', 'What access is still needed?']],
  ['philippines-outsourced-content-calendar-workflow', 'Philippines outsourced content calendar workflow', 'Coordinate briefs, drafts, reviews, and publishing dates without losing ownership.', 'content calendars', ['maintain the calendar', 'check brief completeness', 'prepare review reminders'], ['Who owns final approval?', 'What makes a brief ready?', 'Which dates are locked?']],
  ['philippines-virtual-assistant-meeting-notes', 'Philippines virtual assistant meeting notes workflow', 'Turn meetings into accurate notes, assigned actions, and a visible follow-up list.', 'meeting notes', ['capture decisions', 'assign action owners', 'send a draft recap'], ['What is a decision?', 'Who receives the recap?', 'What requires manager approval?']],
  ['philippines-outsourced-ecommerce-order-support', 'Philippines outsourced ecommerce order support checklist', 'Handle order-status questions with approved replies and clear refund escalation.', 'order support', ['check order status', 'send approved updates', 'escalate refund requests'], ['Which systems are read-only?', 'What is the refund threshold?', 'Who handles complaints?']],
  ['philippines-remote-team-quality-assurance-scorecard', 'Philippines remote team quality assurance scorecard', 'Use a small scorecard to review accuracy, completeness, timeliness, and blockers.', 'quality assurance', ['sample completed work', 'score against examples', 'record corrective coaching'], ['What is a pass?', 'How large is the sample?', 'Who owns repeated misses?']],
  ['philippines-outsourced-vendor-follow-up', 'Philippines outsourced vendor follow-up process', 'Keep vendor requests moving with a tracker, approved messages, and escalation dates.', 'vendor follow-up', ['maintain the tracker', 'send approved reminders', 'flag missed commitments'], ['Which vendors may be contacted?', 'What can be promised?', 'When does the owner step in?']],
  ['philippines-virtual-assistant-file-organization', 'Philippines virtual assistant file organization guide', 'Organize shared files with naming rules, source links, and a reviewable archive.', 'file organization', ['apply naming rules', 'move files to approved folders', 'record uncertain items'], ['Who owns folder access?', 'What must not be moved?', 'How are duplicates handled?']],
  ['philippines-outsourced-social-media-assistance', 'Philippines outsourced social media assistance checklist', 'Define safe research, scheduling, and reporting tasks while keeping publishing approval clear.', 'social media assistance', ['prepare the content queue', 'check links and assets', 'prepare weekly metrics'], ['Who approves copy?', 'Which replies are escalated?', 'What account access is needed?']],
  ['philippines-remote-staff-password-access-review', 'Philippines remote staff password and access review', 'Review named accounts and least-privilege access before expanding a remote role.', 'access review', ['list required accounts', 'remove unused access', 'record the next review date'], ['Who owns each account?', 'Is MFA enabled?', 'How quickly can access be removed?']],
  ['philippines-outsourced-recruiting-coordinator-workflow', 'Philippines outsourced recruiting coordinator workflow', 'Structure candidate scheduling, document collection, and status updates around hiring-manager decisions.', 'recruiting coordination', ['schedule interviews', 'maintain candidate status', 'prepare interview packets'], ['Who makes the hiring decision?', 'Which data is sensitive?', 'What needs approval before sending?']],
  ['philippines-virtual-assistant-project-tracker', 'Philippines virtual assistant project tracker setup', 'Create a simple tracker that makes owners, due dates, blockers, and next actions visible.', 'project tracking', ['update task status', 'check due dates', 'summarize blockers'], ['What counts as done?', 'Who changes priorities?', 'Which blockers are urgent?']],
  ['philippines-outsourced-data-entry-quality-checks', 'Philippines outsourced data entry quality checks', 'Reduce rework with source documents, field rules, sampling, and a correction log.', 'data entry', ['enter approved records', 'run field checks', 'log corrections'], ['What is the source of truth?', 'Which fields are mandatory?', 'Who approves a new pattern?']],
  ['philippines-remote-customer-success-follow-up', 'Philippines remote customer success follow-up routine', 'Keep customer follow-ups consistent with approved templates, dates, and escalation notes.', 'customer success follow-up', ['update the follow-up queue', 'draft check-in messages', 'flag risk signals'], ['Which messages need approval?', 'What is a risk signal?', 'Who owns a dissatisfied customer?']],
  ['philippines-outsourced-marketing-reporting', 'Philippines outsourced marketing reporting checklist', 'Prepare source-linked marketing reports that managers can review quickly.', 'marketing reporting', ['collect approved metrics', 'check source dates', 'prepare a weekly summary'], ['Which metrics matter?', 'What is the reporting period?', 'Who approves the interpretation?']],
].map((row) => {
  const [slug, title, excerpt, focus, tasks, checks] = row as [string, string, string, string, string[], string[]];
  return { slug, title, excerpt, focus, tasks, checks };
});

export const dailyBlogPosts = topics.map(({ slug, title, excerpt }) => ({ slug, title, excerpt, minutes: 10 }));

export const dailyBlogBasics = Object.fromEntries(topics.map(({ slug, focus, tasks, checks }) => [slug, {
  intro: `A useful ${focus} role starts with a small, visible task lane. Give the Philippines-based team member examples, a named reviewer, and written limits before adding more work.`,
  sections: [
    { title: 'Define the starting lane', paragraphs: [`List the first tasks in order and attach one finished example to each. The starting lane should be repeatable and easy for a manager to check. Begin with ${tasks[0]}, then add the next task only after the first output is steady.`, 'Keep decisions about money, pricing, legal matters, hiring, and policy exceptions with your manager. The role can collect facts and prepare a draft, but the owner should approve consequential changes.'], checks },
    { title: 'Set the handoff and review', paragraphs: ['Use one task board, one source-of-truth folder, and one short daily note. The worker should link completed work and record any item that cannot be finished. Review the first five examples against the same checklist.', 'Add exactly the access required for the starting tasks. Use named accounts, multi-factor authentication where available, and a removal owner. Review permissions before expanding the role.'], checks: [...checks, 'Who removes access when the work ends?'] },
    { title: 'Improve after the first week', paragraphs: ['At the end of the first week, compare accuracy, completeness, timeliness, and open questions. Turn repeated corrections into a short SOP or example. This keeps the role useful without making the brief vague.', 'Keep a decision log for exceptions and update the review owner when responsibility changes. A clear escalation path protects both the business and the Philippines-based worker.'], checks: [...checks, 'What evidence supports adding another task?'] },
  ],
}]));
