type Topic={slug:string;title:string;excerpt:string;lane:string;caseStudy:string;source:string;sourceName:string};
const publishedAt='2026-09-25',heroImage='/research-batch-thumbnail.jpg';
const topics:readonly Topic[]=[
{slug:'philippines-accounts-payable-invoice-exception-queue',title:'Build an invoice exception queue for Philippines accounts payable support',excerpt:'Separate routine invoice preparation from tax, bank, duplicate, and approval exceptions so bookkeeping support stays traceable.',lane:'accounts payable exception administration',caseStudy:'A vendor invoice has the expected amount but new bank instructions in the email. The specialist preserves both records and routes independent verification instead of changing payment data.',source:'https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping',sourceName:'IRS small-business recordkeeping guidance'},
{slug:'philippines-help-desk-knowledge-base-review',title:'Run a help-desk knowledge base review with Philippines technical support',excerpt:'Keep troubleshooting articles current through ownership, evidence, approval, expiry, and feedback controls.',lane:'help-desk knowledge base maintenance',caseStudy:'A popular reset article still works for older accounts but omits a new identity check. The specialist flags the affected audience and holds publication until the security owner approves the revised sequence.',source:'https://www.nist.gov/cyberframework',sourceName:'NIST Cybersecurity Framework'},
{slug:'philippines-payroll-input-handoff-checklist',title:'Create a payroll input handoff checklist for Philippines administrative support',excerpt:'Collect approved time, leave, and change records without shifting payroll calculations or employee decisions to an assistant.',lane:'payroll input preparation',caseStudy:'A manager sends a late spreadsheet that conflicts with approved leave in the HR system. The assistant records the conflict and routes it to the payroll owner without selecting a preferred value.',source:'https://www.dol.gov/general/topic/wages/recordkeeping',sourceName:'US Department of Labor recordkeeping guidance'},
{slug:'philippines-podcast-guest-scheduling-workflow',title:'Plan podcast guest scheduling with a Philippines executive assistant',excerpt:'Coordinate guest details, consent, calendars, assets, and production handoffs while editorial decisions remain with the host.',lane:'podcast guest coordination',caseStudy:'A guest proposes a health claim for the episode title after the booking is confirmed. The assistant preserves the request and routes editorial review instead of publishing it in promotional copy.',source:'https://www.ftc.gov/business-guidance/advertising-marketing',sourceName:'FTC advertising and marketing guidance'},
{slug:'philippines-marketplace-return-evidence-workflow',title:'Design a marketplace return evidence workflow for Philippines ecommerce support',excerpt:'Organize return requests, platform deadlines, item evidence, and approved remedies without inventing policy exceptions.',lane:'marketplace return administration',caseStudy:'Tracking shows a returned parcel at the warehouse, but the receiving record names a different SKU. The specialist keeps both facts visible and routes the remedy decision.',source:'https://www.ftc.gov/business-guidance/resources/selling-internet-prompt-delivery-rules',sourceName:'FTC internet order guidance'},
{slug:'philippines-construction-bid-document-control',title:'Set up construction bid document control with Philippines project support',excerpt:'Keep addenda, bidder questions, due dates, acknowledgments, and submission evidence aligned without delegating commercial judgment.',lane:'construction bid administration',caseStudy:'A subcontractor quote arrives before a new addendum that changes the scope. The coordinator links both records and requests an authorized review rather than treating the earlier price as final.',source:'https://www.archives.gov/records-mgmt/policy/records-mgmt-language',sourceName:'US National Archives records-management guidance'},
{slug:'philippines-nonprofit-donor-record-cleanup',title:'Control nonprofit donor record cleanup with a Philippines data specialist',excerpt:'Resolve duplicate and incomplete donor records while protecting preferences, attribution, and restricted personal information.',lane:'nonprofit donor data administration',caseStudy:'Two records share an email but contain different consent preferences and household names. The specialist holds the merge until the data owner resolves identity and retention rules.',source:'https://www.ftc.gov/business-guidance/privacy-security',sourceName:'FTC privacy and data-security guidance'},
{slug:'philippines-dental-recall-scheduling-queue',title:'Build a dental recall scheduling queue with Philippines patient support',excerpt:'Coordinate approved reminders and appointment options with minimum necessary access and clear clinical escalation.',lane:'dental recall scheduling administration',caseStudy:'A patient replies to a routine reminder with symptoms and asks whether treatment can wait. The scheduler routes the clinical question and avoids offering medical guidance.',source:'https://www.hhs.gov/hipaa/for-professionals/privacy/guidance/minimum-necessary-requirement/index.html',sourceName:'HHS HIPAA minimum necessary guidance'},
{slug:'philippines-proof-of-delivery-reconciliation',title:'Reconcile proof of delivery with Philippines logistics support',excerpt:'Match shipment, carrier, recipient, and exception evidence without allowing administrative closeout to decide liability.',lane:'proof-of-delivery reconciliation',caseStudy:'The carrier image shows a doorway, while the recipient reports non-delivery and the address label is unreadable. The specialist records each source and escalates the disputed outcome.',source:'https://www.archives.gov/records-mgmt/policy/records-mgmt-language',sourceName:'US National Archives records-management guidance'},
{slug:'philippines-security-questionnaire-intake',title:'Prepare security questionnaire intake with a Philippines operations specialist',excerpt:'Route customer security questions to evidence owners without guessing controls, certifications, or commitments.',lane:'security questionnaire administration',caseStudy:'A questionnaire asks whether every vendor is continuously monitored, but the approved evidence covers annual reviews. The specialist cites the available record and routes the gap instead of answering yes.',source:'https://www.nist.gov/privacy-framework',sourceName:'NIST Privacy Framework'},
{slug:'philippines-purchase-request-triage',title:'Triage purchase requests with a Philippines procurement assistant',excerpt:'Check completeness, budget references, vendor records, conflicts, and approvals while purchasing authority stays with accountable owners.',lane:'purchase request administration',caseStudy:'A requester marks an order urgent but provides a personal payment link rather than an approved vendor record. The assistant holds the request and routes vendor verification.',source:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',sourceName:'FTC guide to protecting personal information'},
{slug:'philippines-insurance-renewal-document-preparation',title:'Prepare insurance renewal documents with Philippines administrative support',excerpt:'Build a dated evidence pack for renewal review without interpreting coverage, risk, or policy suitability.',lane:'insurance renewal administration',caseStudy:'The current asset schedule and finance export disagree on an equipment value. The specialist preserves both sources and requests an owner decision instead of normalizing the number.',source:'https://content.naic.org/consumer',sourceName:'National Association of Insurance Commissioners consumer resources'}
];
const body=(t:Topic)=>[
`Start with the business outcome for ${t.lane}, not a broad job description. Name the eligible work, the expected result, the system of record, and the person who reviews it. State what must remain unchanged. A narrow first lane helps a Philippines-based specialist learn the real work and gives the manager a fair way to inspect quality before scope grows.`,
`Create one controlled intake record. Capture the item identifier, source, received time and time zone, required fields, owner, target, sensitivity, and current status. Mark values as verified, supplied but unverified, missing, conflicting, or not applicable. Link approved sources rather than copying restricted material into chat, personal notes, or unmanaged spreadsheets.`,
`Define ready before work begins. A ready item is in scope, attributable to a permitted source, complete enough for the next safe action, assigned to a named worker, and paired with a verification method. Keep duplicates, incomplete requests, and out-of-scope work visible. Never restart a difficult case in a cleaner record that loses its history.`,
`Separate preparation, execution, approval, and verification. The specialist may gather evidence, apply explicit rules, prepare an approved action, and route exceptions. Financial, legal, employment, security, policy, and customer-commitment decisions stay with accountable owners. Urgency or approval on a similar item does not silently expand authority.`,
`Use minimum necessary access. Give each person an individual account and the smallest permission set that supports the defined lane. Keep passwords, payment details, identity documents, health information, privileged material, and irrelevant personal data out of general work records. Name the access owner, test removal, and record temporary grants with an expiry.`,
`Write hold conditions before launch. Hold an item when identity is uncertain, sources disagree, required evidence is missing, requested action exceeds the written boundary, or no owner can approve it. A useful hold note states observed facts, safe steps already completed, the smallest decision needed, its owner, operational impact, and the next review time.`,
`Consider a realistic case: ${t.caseStudy} This control prevents a plausible shortcut from changing money, access, rights, public information, or customer expectations before an accountable person sees the evidence. It also gives the decision owner a compact record instead of forcing them to reconstruct events from messages.`,
`Use a written communication rule. Say which acknowledgments and routine updates may be sent from approved language, which drafts need review, and which subjects belong in a restricted channel. Acknowledge receipt without promising an outcome. Separate confirmed facts, a sender's statement, and an internal hypothesis. Use explicit local dates and time zones.`,
`Build a small exception queue beside routine work. Show reason, age, owner, next decision, and next review time. Do not hide blocked items by closing them, moving them to private notes, or resetting their age. Review the oldest and highest-consequence exceptions first, then fix repeated causes in the intake form, permission set, example, or owner map.`,
`Review quality against a defined population and cutoff. Check source identity, required fields, rule version, authority boundary, destination state, and communication. Record the precise defect and affected item. Report a numerator with its denominator. A risk-weighted sample can expose important failures, but it is not a pass rate for work that nobody inspected.`,
`Completion requires destination evidence. A sent email, saved form, uploaded file, changed label, or checked box is an event rather than proof. Reopen the destination, compare it with the controlling source, and record who verified it, when, and with what limitation. If verification is unavailable, keep the item open with a named recovery action.`,
`Run a controlled first week. Test a normal item, an incomplete item, a duplicate or conflicting item, and an escalation. Review early work frequently. Correct the durable rule, template, example, or access setting that caused confusion; private coaching alone will not help the next worker or make the process auditable.`,
`After one full cycle, inspect missing inputs, repeat holds, reopened work, access mismatches, slow owner decisions, and verification failures. Expand volume only when routine outcomes are reproducible and exceptions remain visible. Add authority only through a written rule with an owner, evidence requirement, effective date, review date, and tested rollback.`,
`Use ${t.sourceName} as an authoritative starting point for the control it supports. Record the relevant proposition and retrieval date. Apply it through current company policy, contracts, platform rules, jurisdiction, and qualified advice. A public source provides context; it does not grant an assistant permission to make a regulated or consequential decision.`,
`Turn the design into a one-page role brief: first tasks, tools, working hours, handoff window, access limits, approval owner, stop conditions, and review cadence. OutsourcedPhilippines.com can help shape a focused brief for Philippines-based talent. Bring the messy task list while keeping final business decisions with accountable owners.`
];
export const sep25BlogPosts=topics.map(({slug,title,excerpt})=>({slug,title,excerpt,minutes:12,publishedAt,heroImage}));
export const sep25BlogBasics=Object.fromEntries(topics.map(t=>[t.slug,{intro:`A practical starting point for ${t.lane} with Philippines-based support.`,routeBody:body(t),sources:[{name:t.sourceName,url:t.source}],sections:[{title:'Define the lane',paragraphs:['Write the eligible population, source systems, expected output, and reviewer before live work begins.','Use examples of ready, held, and out-of-scope cases.'],checks:['What makes an item ready?','Which source controls?','Who approves exceptions?']},{title:'Verify before closeout',paragraphs:['Check the destination against the controlling source and preserve limitations.','Keep failed and reopened work visible.'],checks:['What proves the result?','Who verified it?','Is recovery owned?']}]}]));
