type Topic={slug:string;title:string;excerpt:string;lane:string;caseStudy:string;source:string;sourceName:string};
const publishedAt='2026-09-24',heroImage='/research-batch-thumbnail.jpg';
const topics:readonly Topic[]=[
{slug:'philippines-customer-support-refund-authority-matrix',title:'Build a refund authority matrix for a Philippines customer support team',excerpt:'Separate evidence gathering, approved remedies, exceptions, and financial approval so agents can move quickly without inventing authority.',lane:'customer support refund handling',caseStudy:'A parcel is marked delivered, but the buyer requests a full refund. The agent preserves the carrier event and the customer statement, then routes the disputed-delivery decision rather than treating either claim as conclusive.',source:'https://www.ftc.gov/business-guidance/resources/selling-internet-prompt-delivery-rules',sourceName:'FTC internet order guidance'},
{slug:'philippines-ecommerce-product-catalog-change-queue',title:'Run a controlled product-catalog change queue with Philippines ecommerce support',excerpt:'Keep prices, descriptions, inventory claims, and publishing approvals traceable when an assistant maintains a live catalog.',lane:'ecommerce catalog administration',caseStudy:'A supplier sheet shows a lower price than the approved promotion file. The assistant holds the price while completing safe alt-text and category updates.',source:'https://www.ftc.gov/business-guidance/advertising-marketing',sourceName:'FTC advertising and marketing guidance'},
{slug:'philippines-executive-assistant-business-travel-brief',title:'Create a business travel brief with a Philippines executive assistant',excerpt:'Turn approved itinerary details into a useful brief while protecting personal data and keeping booking decisions with the traveler.',lane:'executive travel administration',caseStudy:'A schedule change leaves too little transfer time. The assistant presents supported alternatives and their conditions without rebooking independently.',source:'https://travel.state.gov/content/travel/en/international-travel.html',sourceName:'US Department of State international travel guidance'},
{slug:'philippines-property-maintenance-vendor-dispatch',title:'A property maintenance vendor-dispatch workflow for Philippines support staff',excerpt:'Route maintenance requests with clear safety triggers, access preferences, vendor authority, and closeout evidence.',lane:'property maintenance coordination',caseStudy:'A tenant reports a ceiling stain beneath an upstairs unit. The coordinator records the observation and activates the inspection route without diagnosing the cause.',source:'https://www.epa.gov/indoor-air-quality-iaq',sourceName:'US EPA indoor air quality guidance'},
{slug:'philippines-accounts-receivable-follow-up-workflow',title:'Design an accounts-receivable follow-up workflow for Philippines bookkeeping support',excerpt:'Organize invoice reminders, dispute evidence, promises to pay, and escalation without letting an assistant alter financial terms.',lane:'accounts-receivable administration',caseStudy:'A customer says an invoice was paid and supplies a partial screenshot. The specialist records the claim and routes reconciliation rather than marking it settled.',source:'https://www.irs.gov/businesses/small-businesses-self-employed/recordkeeping',sourceName:'IRS small-business recordkeeping guidance'},
{slug:'philippines-recruitment-interview-scheduling-workflow',title:'Build a fair interview-scheduling workflow with a Philippines recruitment assistant',excerpt:'Coordinate availability, accommodations, interviewer coverage, and updates while hiring judgments stay with the employer.',lane:'recruitment scheduling',caseStudy:'A candidate asks for a health-related adjustment. The coordinator uses the confidential accommodation route and retains only the operational detail needed to schedule.',source:'https://www.eeoc.gov/employers/small-business',sourceName:'US EEOC small-business guidance'},
{slug:'philippines-crm-lead-routing-rules',title:'Set CRM lead-routing rules for a Philippines sales support specialist',excerpt:'Use source-based ownership, territory, duplicate, and escalation rules so fast assignment does not corrupt the CRM.',lane:'CRM lead routing',caseStudy:'A form matches an existing customer domain but names another subsidiary. The specialist holds assignment for the account owner instead of creating a competing record.',source:'https://www.ftc.gov/business-guidance/privacy-security',sourceName:'FTC privacy and data-security guidance'},
{slug:'philippines-social-media-comment-moderation-playbook',title:'A social media comment moderation playbook for Philippines support teams',excerpt:'Define response, hiding, evidence, crisis, and escalation rules before delegating public community work.',lane:'social media comment moderation',caseStudy:'A customer posts an order number and phone number in a complaint. The moderator uses the privacy route and avoids repeating the details.',source:'https://www.ftc.gov/business-guidance/resources/advertising-marketing-internet-rules-road',sourceName:'FTC internet advertising guidance'},
{slug:'philippines-saas-customer-onboarding-queue',title:'Run a SaaS customer onboarding queue with Philippines operations support',excerpt:'Coordinate setup tasks, dependencies, access, updates, and acceptance without turning administration into product authority.',lane:'SaaS onboarding coordination',caseStudy:'A customer requests an integration absent from the order. The coordinator logs it and routes scope and security review rather than enabling it.',source:'https://www.nist.gov/privacy-framework',sourceName:'NIST Privacy Framework'},
{slug:'philippines-legal-intake-conflict-check-preparation',title:'Prepare legal intake for conflict review with a Philippines administrative specialist',excerpt:'Collect names, matter context, documents, and urgency while authorized owners retain legal and conflict decisions.',lane:'legal intake administration',caseStudy:'A caller alleges a filing is due tomorrow and asks whether the firm represents them. The specialist escalates without giving assurance or advice.',source:'https://www.americanbar.org/groups/professional_responsibility/resources/model_rules_of_professional_conduct/',sourceName:'American Bar Association Model Rules resources'},
{slug:'philippines-insurance-claim-document-index',title:'Build an insurance claim document index with Philippines administrative support',excerpt:'Keep submitted records attributable and reviewable without allowing an assistant to interpret coverage or decide a claim.',lane:'insurance claim document administration',caseStudy:'Two estimates name different damaged items. The specialist indexes both and flags the conflict without choosing which description is correct.',source:'https://www.ftc.gov/business-guidance/resources/protecting-personal-information-guide-business',sourceName:'FTC guide to protecting personal information'},
{slug:'philippines-operations-recurring-task-retirement-review',title:'Review and retire recurring tasks with a Philippines operations coordinator',excerpt:'Remove obsolete work using ownership, dependency, retention, and verification checks instead of silently deleting reminders.',lane:'recurring operations governance',caseStudy:'A weekly sheet appears unused, but its totals feed a monthly customer report. The coordinator keeps it active until the report owner confirms a replacement.',source:'https://www.archives.gov/records-mgmt/policy/records-mgmt-language',sourceName:'US National Archives records-management guidance'}
];
const body=(t:Topic)=>[
`Start with the business outcome for ${t.lane}, not a broad job description. Name the eligible work, the expected result, the system of record, and the person who reviews it. State what must remain unchanged. A narrow first lane helps a Philippines-based specialist learn the real work and gives the manager a fair way to inspect quality before scope grows.`,
`Create one controlled intake record. Capture the item identifier, source, received time and time zone, required fields, owner, target, sensitivity, and current status. Mark values as verified, supplied but unverified, missing, conflicting, or not applicable. Link approved sources rather than copying restricted material into chat, personal notes, or unmanaged spreadsheets.`,
`Define ready before work begins. A ready item is in scope, attributable to a permitted source, complete enough for the next safe action, assigned to a named worker, and paired with a verification method. Keep duplicates, incomplete requests, and out-of-scope work visible. Never restart a difficult case in a cleaner record that loses its history.`,
`Separate preparation, execution, approval, and verification. The specialist may gather evidence, apply explicit rules, prepare an approved action, and route exceptions. Financial, legal, employment, security, policy, and customer-commitment decisions stay with accountable owners. Urgency or approval on a similar item does not silently expand authority.`,
`Use minimum necessary access. Give each person an individual account and the smallest permission set that supports the defined lane. Keep passwords, payment details, identity documents, health information, privileged material, and irrelevant personal data out of general work records. Name the access owner, test removal, and record temporary grants with an expiry.`,
`Write hold conditions before launch. Hold an item when identity is uncertain, sources disagree, required evidence is missing, requested action exceeds the written boundary, or no owner can approve it. A useful hold note states observed facts, safe steps already completed, the smallest decision needed, its owner, operational impact, and the next review time.`,
`Consider a realistic case: ${t.caseStudy} This control prevents a plausible shortcut from changing money, access, rights, public information, or customer expectations before an accountable person sees the evidence. It also gives the decision owner a compact record instead of forcing them to reconstruct events from messages.`,
`Use a written communication rule. Say which acknowledgments and routine updates may be sent from approved language, which drafts need review, and which subjects belong in a restricted channel. Acknowledge receipt without promising an outcome. Separate confirmed facts, a sender's statement, and an internal hypothesis. Use explicit local dates and time zones.`,
`Build a small exception queue beside routine work. Show reason, age, owner, next decision, and next review time. Do not hide blocked items by closing them, moving them to private notes, or resetting their age. Review the oldest and highest-consequence exceptions first, then fix repeated causes in the intake form, permission set, example, or owner map.`,
`Review quality against a defined population and cutoff. Check source identity, required fields, rule version, authority boundary, destination state, and communication. Record the precise defect and affected item. Report a numerator with its denominator. A risk-weighted sample can expose important failures, but it is not a pass rate for work that nobody inspected.`,
`Completion requires destination evidence. A sent email, saved form, uploaded file, changed label, or checked box is an event rather than proof. Reopen the destination, compare it with the controlling source, and record who verified it, when, and with what limitation. If verification is unavailable, keep the item open with a named recovery action.`,
`Run a controlled first week. Test a normal item, an incomplete item, a duplicate or conflicting item, and an escalation. Review early work frequently. Correct the durable rule, template, example, or access setting that caused confusion; private coaching alone will not help the next worker or make the process auditable.`,
`After one full cycle, inspect missing inputs, repeat holds, reopened work, access mismatches, slow owner decisions, and verification failures. Expand volume only when routine outcomes are reproducible and exceptions remain visible. Add authority only through a written rule with an owner, evidence requirement, effective date, review date, and tested rollback.`,
`Use ${t.sourceName} as an authoritative starting point for the control it supports. Record the relevant proposition and retrieval date. Apply it through current company policy, contracts, platform rules, jurisdiction, and qualified advice. A public source provides context; it does not grant an assistant permission to make a regulated or consequential decision.`,
`Turn the design into a one-page role brief: first tasks, tools, working hours, handoff window, access limits, approval owner, stop conditions, and review cadence. OutsourcedPhilippines.com can help shape a focused brief for Philippines-based talent. Bring the messy task list while keeping final business decisions with accountable owners.`
];
export const sep24BlogPosts=topics.map(({slug,title,excerpt})=>({slug,title,excerpt,minutes:12,publishedAt,heroImage}));
export const sep24BlogBasics=Object.fromEntries(topics.map(t=>[t.slug,{intro:`A practical starting point for ${t.lane} with Philippines-based support.`,routeBody:body(t),sources:[{name:t.sourceName,url:t.source}],sections:[{title:'Define the lane',paragraphs:['Write the eligible population, source systems, expected output, and reviewer before live work begins.','Use examples of ready, held, and out-of-scope cases.'],checks:['What makes an item ready?','Which source controls?','Who approves exceptions?']},{title:'Verify before closeout',paragraphs:['Check the destination against the controlling source and preserve limitations.','Keep failed and reopened work visible.'],checks:['What proves the result?','Who verified it?','Is recovery owned?']}]}]));
