type Topic = {
  slug: string;
  title: string;
  excerpt: string;
  opening: string;
  situation: string;
  ownerDecision: string;
  assistantWork: string;
  evidence: string;
  failure: string;
  example: string;
  measure: string;
  handoff: string;
  close: string;
  headings: readonly [string, string, string, string, string];
};

const publishedAt = '2026-09-03';

const topics: readonly Topic[] = [
  {
    slug: 'philippines-content-assistant-morning-brief',
    title: 'A morning brief for a Philippines content assistant',
    excerpt: 'Turn the daily article target into a bounded assignment with sources, ownership, review timing, and a safe hold state.',
    opening: 'Daily publishing often goes wrong before anybody writes a sentence. A topic arrives without a reader question, an editor assumes the researcher knows which sources count, and the review window is mentioned only after the draft appears. A morning brief gives a Philippines-based content assistant a reliable starting point. It should make one article movable without pretending that every decision has already been made.',
    situation: 'The useful unit is one proposed route for one reader problem. Record the working title, intended slug, content family, reader, publication date, factual boundaries, permitted sources, and the person who will approve public claims. Add the expected handoff time in one time zone. If any required field is missing, the article remains in intake. A crowded calendar is not a reason to convert an incomplete idea into a writing assignment.',
    ownerDecision: 'The commissioning editor decides why the article belongs on the site, which service or operating problem it supports, and what claim the evidence must be able to sustain. The editor also owns publication priority and any exception involving a sensitive assertion. Those choices should appear in the brief rather than being inferred from a previous article or a private conversation.',
    assistantWork: 'The assistant can check the proposed slug against the corpus, assemble approved source material, draft a question-led outline, note missing evidence, and prepare a review copy. The role does not include inventing company experience, choosing a commercial promise, changing the campaign date, or releasing a held route. Clear limits make independent preparation possible because the assistant knows what can continue while a decision waits.',
    evidence: 'Attach source notes beside the parts of the outline they support. Each note should identify the publisher, page or document, relevant date, exact point observed, and any limitation. Company-supplied statements need an owner and approval state. A link alone is not evidence of fit. The morning brief should say whether a source establishes a fact, provides background, or merely suggests a question worth investigating.',
    failure: 'A weak brief usually produces one of two bad outcomes: a polished article that answers the wrong question, or a stalled draft whose writer keeps requesting context piecemeal. Watch for generic verbs such as research, improve, or optimize with no visible finish condition. Replace them with an observable artifact, such as a source table, a six-part outline, or a draft ready for a named editor.',
    example: 'Suppose the topic concerns handing customer support reports to a manager. The brief can define the reader as an operations lead, require examples about queue evidence and escalation, exclude invented performance results, and route refund or policy wording to the account owner. The assistant can then research and draft the operating steps while the manager retains customer-policy decisions. The division is specific enough to work across a time-zone handoff.',
    measure: 'Review brief quality through return reasons, not activity volume. Track missing reader definitions, route collisions, unavailable sources, unclear approval owners, and questions discovered after drafting began. Sample the original brief beside the returned draft. A shorter drafting time is useful only when the article also arrives within scope and with a traceable evidence record.',
    handoff: 'At the end of the work window, send the current route, draft link, sources checked, open questions, next permitted action, reviewer, and requested response time. Name the exact condition for resuming a held item. This lets a manager answer one decision without reconstructing the whole assignment and lets the next contributor distinguish completed preparation from publication approval.',
    close: 'A morning brief earns its place when it reduces ambiguity without hiding it. Keep the form short enough to use every day, but require the fields that protect public meaning. After several releases, remove questions that never influence work and strengthen the ones repeatedly associated with corrections. The routine should become more precise as the team learns, not longer by default.',
    headings: ['Define the article before the task', 'Keep decisions with the editor', 'Make evidence usable', 'Test the brief on a real handoff', 'Improve the intake from returns'],
  },
  {
    slug: 'philippines-outsourced-source-freshness-watch',
    title: 'Source freshness watch for an outsourced Philippines editorial team',
    excerpt: 'Monitor material references by claim, change signal, review owner, and the consequence of stale evidence.',
    opening: 'A source can continue returning HTTP 200 long after it stops supporting an article. Definitions change, guidance is revised, tables gain a new period, and service pages quietly narrow their language. A source freshness watch gives an outsourced Philippines editorial team a manageable way to find those changes without treating every old link as an emergency.',
    situation: 'Start with the claims whose meaning depends on an outside authority or a dated company instruction. For each claim, record its canonical route, source URL, publisher, observed period, retrieval date, review owner, and consequence if the source changes. This is a claim register, not a bookmark collection. One source may support several statements, and each statement may need a different response when the page changes.',
    ownerDecision: 'The editor decides which claims are material, how often they need review, and whether a changed source requires clarification, correction, retirement, or no action. Legal, employment, financial, health, and security interpretations should go to the appropriate subject owner. A monitoring role can surface evidence but should not make a specialist decision look settled.',
    assistantWork: 'A Philippines-based researcher can revisit approved URLs, compare titles and dates, capture changed passages, note redirects, and open a review item. They may repair an unambiguous internal link when that authority is granted. They should not swap in a merely similar source, broaden a sentence to avoid a mismatch, or change historical publication dates. The observation must remain separate from the editorial response.',
    evidence: 'Store a compact before-and-after note. Include the old proposition as recorded, the current source language in a brief compliant excerpt or paraphrase, the observation time, and the affected route. When a machine comparison flags a page, a person still needs to decide whether navigation, boilerplate, or substantive guidance changed. Preserve uncertainty instead of labeling every diff a correction.',
    failure: 'Freshness programs become noisy when they monitor whole pages without claim context. The queue fills with cookie-banner changes and layout edits while a small number of material assertions receive no attention. Another failure is silent repair: a contributor replaces a citation and closes the ticket without checking whether the article sentence still means the same thing. Both patterns destroy the audit trail.',
    example: 'Imagine a workforce data page publishes a newer annual table. The researcher records the new period and identifies the article paragraph that used the earlier table for context. The editor may decide that the older period remains appropriate for a historical comparison, that the article needs an update, or that the claim should be removed. The changed source triggers a decision; it does not dictate one.',
    measure: 'Useful measures include material claims reviewed, confirmed changes, false alarms, age of owner decisions, and repeated sources that create many findings. Do not present the percentage of working links as a content-accuracy score. Link health and claim support overlap, but they are not the same test. Keep examples beside aggregate counts so the editor can adjust review intervals intelligently.',
    handoff: 'A freshness finding should state what changed, which public sentence may be affected, what the source now supports, what remains uncertain, and who owns the next decision. If the route can safely remain public during review, say so. If the current wording could mislead readers, identify the escalation path and hold any proposed replacement until it is approved.',
    close: 'Run the watch according to risk rather than treating all sources equally. A stable definition page may need a different interval from a frequently updated dashboard. Review the schedule after real changes occur. The goal is a small, explainable queue that helps editors protect useful articles, not a stream of automated alerts that everybody learns to ignore.',
    headings: ['Build a claim register', 'Separate observation from response', 'Capture meaningful changes', 'Tune review intervals', 'Close with an editorial decision'],
  },
  {
    slug: 'philippines-editorial-backlog-capacity-board',
    title: 'An editorial backlog capacity board for a Philippines remote team',
    excerpt: 'Plan daily article work from ready briefs, constrained review capacity, aging decisions, and honest hold states.',
    opening: 'An editorial backlog can look healthy while hiding work that has no chance of being reviewed. Counting topics rewards intake, not publication readiness. A capacity board for a Philippines remote team should show which articles can move today, which scarce review step limits them, and which items wait for an owner decision.',
    situation: 'Give each article one state based on observable conditions: intake, ready for research, drafting, evidence review, owner decision, formatting, release check, or held. Define entry and exit rules. A draft is not in evidence review merely because the writer finished typing; the required source notes must be present and a reviewer must have accepted the queue. Make blocked work visible without treating it as failed output.',
    ownerDecision: 'The editorial lead owns priority, work-in-progress limits, reviewer allocation, and exceptions to the release plan. Subject owners decide sensitive claims. A support coordinator can display tradeoffs but cannot decide that a late campaign item outranks a correction, or that an unavailable reviewer may be bypassed. Capacity choices influence public risk and need accountable ownership.',
    assistantWork: 'A Philippines-based coordinator can reconcile queue states, check that briefs meet entry rules, flag aging items, prepare daily options, and move records after documented events. They can also identify work that is safe to prepare during a hold. The coordinator should not mark an article approved from an ambiguous message or split one route into duplicate cards to make throughput look better.',
    evidence: 'Every state change should point to the artifact that caused it: accepted brief, draft, evidence note, recorded decision, corrected page, or release verification. Keep dates in one time zone and distinguish the time work entered a state from the time somebody last commented. Without those fields, aging reports often reward conversation rather than progress.',
    failure: 'The board fails when every stage has unlimited capacity. Writers start more drafts, reviewers receive an unranked pile, and urgent questions arrive through chat. It also fails when held work disappears from the main view. A hidden blocker cannot be managed, and a forgotten route may later be reintroduced under a new identity, creating duplicate content and confused publication history.',
    example: 'Consider a day with four ready briefs and one specialist review slot. The lead may select the article with a time-sensitive source, allow two other writers to prepare non-sensitive sections, and hold the fourth because its reader question remains unclear. The board records why. It does not imply that all four items will publish, and it does not count preparation as approval.',
    measure: 'Track time in state, returned work by reason, blocked age, reviewer demand, and the difference between started and released articles. Use medians with representative cases when volume permits, because one exceptional hold can distort an average. The purpose is to find a constraint or weak entry rule, not to rank contributors from a small and mixed queue.',
    handoff: 'The daily board handoff should name current state, last qualifying event, next action, required owner, and earliest review window. Summarize capacity conflicts as choices: which item moves if the specialist takes it, and what waits as a result. This gives the lead a decision they can make quickly without granting the coordinator silent authority over priorities.',
    close: 'Keep the board smaller than the work itself. Link to evidence instead of copying whole drafts into cards. Retire states that never change decisions and add a state only when the team repeatedly loses information at that boundary. A useful capacity board tells the truth about waiting and makes tomorrow’s starting point obvious.',
    headings: ['Define observable states', 'Limit work at the constraint', 'Keep holds in view', 'Read capacity without blame', 'Hand off tomorrow’s starting point'],
  },
  {
    slug: 'philippines-virtual-assistant-internal-link-review',
    title: 'Internal link review by a Philippines virtual assistant',
    excerpt: 'Use reader intent, destination fit, anchor clarity, and route ownership to maintain useful internal article links.',
    opening: 'Internal links are easy to add and surprisingly easy to misuse. A destination may exist yet answer a different question, an anchor may promise more than the page contains, or several articles may send readers around a loop. A Philippines virtual assistant can run a disciplined link review when the task is framed as reader-path evidence rather than mechanical link insertion.',
    situation: 'Review one canonical article in the context of the question that brought a reader there. List each internal link, its anchor, destination, section, and intended job. A link may explain a term, provide a next operating step, connect a relevant service, or offer deeper research. If its purpose cannot be stated plainly, it may be decorative rather than useful.',
    ownerDecision: 'The content owner decides the site’s topic relationships, commercial path, canonical strategy, and whether two articles overlap enough to require restructuring. Service owners approve statements that position a service as the next step. The reviewer can identify a mismatch but should not rewrite the site architecture or invent a conversion claim to justify a link.',
    assistantWork: 'The assistant can crawl or manually inspect approved routes, test response status, compare anchor wording with the destination heading, flag redirects, and propose context-specific changes. They may correct a clear typo under an agreed rule. Adding new service claims, merging routes, changing canonicals, or deleting an established article remains outside routine link maintenance.',
    evidence: 'A finding should contain the source route, exact paragraph, anchor text, destination, response status, destination heading, and a short explanation of fit or mismatch. Screenshots can help with navigation defects, but text evidence matters most for meaning. Retain the observation date because a route that fits today may change later.',
    failure: 'A quota such as add five internal links to every article encourages irrelevant connections and repeated anchors. Another weak practice is judging links from a spreadsheet without reading the surrounding sentence. Both approaches optimize link count while making the reader’s path less predictable. Broken-link detection is useful, but it cannot decide whether a working link belongs.',
    example: 'An article about preparing customer support escalation evidence might link to the customer support service page for role scope and to a research note about review sampling for method detail. It should not link to an unrelated administrative service simply because that page needs traffic. The assistant records the reader job for each proposed connection, and the owner approves material positioning.',
    measure: 'Count broken destinations, redirected routes, misleading anchors, unsupported service paths, orphaned articles, and accepted repair proposals. Sample reader paths before drawing conclusions about the whole corpus. Click counts can show behavior but not whether the link answered the reader’s need, so combine analytics with direct content review rather than presenting either as proof alone.',
    handoff: 'Return proposed edits with the original sentence, revised sentence, destination check, reason, and approval owner. Group purely technical corrections separately from editorial changes. After approval, inspect the rendered page and destination, then record the result. A source-code change is not enough when routing, caching, or generated markup can alter what readers receive.',
    close: 'A good internal link review leaves fewer, clearer choices. Readers should understand why a destination is relevant before clicking. Revisit high-use templates and newly changed service pages first, then sample older articles. The routine belongs in content maintenance, not as a one-time search exercise performed only after links begin failing.',
    headings: ['Give every link a reader job', 'Inspect meaning as well as status', 'Avoid link-count quotas', 'Route commercial changes correctly', 'Retest the rendered path'],
  },
  {
    slug: 'philippines-outsourced-subject-matter-question-routing',
    title: 'Subject-matter question routing for outsourced Philippines content work',
    excerpt: 'Turn uncertain claims into narrow, answerable questions for the owner who has authority to resolve them.',
    opening: 'Writers often lose more time waiting on broad requests for review than they spend resolving the underlying issue. A subject-matter expert receives an entire draft with no indication of what needs judgment. Question routing changes that handoff. A Philippines-based content specialist prepares the evidence and asks one bounded question of the person who can decide it.',
    situation: 'Open a question when a source conflict, company fact, regulated interpretation, service boundary, customer promise, or technical statement cannot be settled within the writer’s authority. Identify the exact route and sentence, what the draft currently says, what the available evidence supports, and the consequence of choosing each option. Keep unrelated copy out of the request.',
    ownerDecision: 'The editorial owner assigns subject domains and named backups. The subject expert decides the substantive point; the publisher decides how that answer appears publicly. Those may be different people. A response from somebody knowledgeable but unauthorized should remain advice until the accountable owner accepts it. The routing map needs this distinction.',
    assistantWork: 'A Philippines-based specialist can research the issue, compare approved sources, quote or paraphrase the relevant passages, propose cautious wording, and maintain the question queue. They may continue sections that do not depend on the answer. They should not infer approval from delay, combine separate expert opinions into a fabricated consensus, or choose the answer that best preserves the deadline.',
    evidence: 'Use a short packet with the proposed claim, source list, contradictions, known company context, open assumption, and requested decision. Mark confidential material so it does not flow into the public draft. If the question depends on current external guidance, include the observation date. The expert should be able to answer without searching for the affected paragraph.',
    failure: 'Sending please review creates avoidable delay because the recipient must diagnose the question before answering it. Tagging several owners without naming a decider creates a second failure: parallel comments arrive, but nobody knows which one controls. A third problem appears when the writer quietly changes the question after receiving an answer. Preserve the request and link any follow-up.',
    example: 'Suppose an article describes which customer complaint decisions a remote support hire can prepare. The writer can document factual workflow options, but the company’s escalation promise belongs to the service owner. The routed question identifies the proposed boundary and asks who approves exceptions. Once answered, the editor incorporates the decision without attributing broader results to the workflow.',
    measure: 'Track questions returned for missing context, time to first usable answer, reopened decisions, repeated categories, and articles held by unavailable owners. Avoid turning expert response time into an individual performance score without workload and priority context. The pattern should improve routing rules and briefing quality, not punish the people protecting sensitive claims.',
    handoff: 'Record the decision verbatim enough to preserve meaning, the decider, date, affected routes, and any condition or review date. Tell the writer exactly what may resume. If the answer changes company policy or multiple pages, open a separate governed change instead of quietly extending one article comment across the corpus.',
    close: 'The best routing system makes fewer questions necessary over time. Repeated answers should become approved examples or documented boundaries, with an owner and review date. Keep true exceptions visible. A knowledge base is useful only when it does not turn an old answer into permanent authority after the underlying policy changes.',
    headings: ['Recognize a real expert question', 'Send the smallest useful packet', 'Name one accountable decider', 'Preserve the answer and its scope', 'Convert repetition into guidance'],
  },
  {
    slug: 'philippines-content-approval-service-window',
    title: 'Designing a content approval window for a Philippines team',
    excerpt: 'Set predictable review windows that respect time-zone handoffs without turning deadlines into silent approval.',
    opening: 'Distributed content teams need predictable decisions more than constant availability. When review requests can arrive at any hour and every item is labeled urgent, writers either wait indefinitely or guess. An approval window gives a Philippines-based team a known time for decisions while preserving the owner’s authority over claims and release.',
    situation: 'Define which artifacts enter the window, the cutoff for a complete request, the reviewer, the response types, and what happens when capacity is full. Separate evidence review, business approval, and release verification when different owners perform them. A request that misses required fields moves to the next eligible window unless a named owner accepts an exception.',
    ownerDecision: 'The publisher owns the schedule, priority exceptions, substitute reviewers, and the meaning of approval. A subject owner retains decisions within their specialty. Silence, an emoji, or attendance at a meeting is not approval unless the organization has explicitly defined and tested that signal. The record should show who accepted the final public meaning.',
    assistantWork: 'A Philippines-based coordinator can assemble decision packets, check completeness, queue requests, notify reviewers, capture responses, and return precise corrections. They can continue formatting or source organization that does not alter held claims. They cannot self-approve because a window closes, reinterpret a conditional answer, or publish an item that lacks the required decision.',
    evidence: 'Every request should include route identity, publication date, review version, material claims, source record, unresolved questions, and the exact action requested. Every response should identify approval, return, or hold, with a reason and affected scope. Keeping the request and response together prevents an old approval from being applied to a later draft that changed materially.',
    failure: 'Approval windows fail when they become meetings where reviewers first encounter unfinished work. They also fail when deadlines are used to transfer risk to the reviewer: respond by noon or we publish. A window is a capacity promise, not forced consent. When the reviewer cannot decide, the honest result is a hold with the next action named.',
    example: 'A team might collect complete requests before the Philippines workday ends and place them in an owner’s morning review queue. The owner approves two, returns one unsupported claim, and holds another for a specialist. The coordinator records each outcome and prepares allowed corrections. The four articles do not share a status merely because they entered together.',
    measure: 'Observe complete requests received, decisions by type, returns caused by missing evidence, holds by owner, and age to the next actionable response. Compare planned capacity with actual demand. Do not treat a high approval rate as quality; it could indicate excellent preparation or superficial review. Sample the evidence packets and corrections to understand the number.',
    handoff: 'At the close of the window, send a compact ledger of approved versions, returned items, holds, owners, and next eligible times. Call out any route whose requested date is at risk. The coordinator should not promise recovery. A clear ledger lets the publishing lead adjust the plan from facts rather than discovering missing approval during release checks.',
    close: 'Review the window after several ordinary cycles and at least one high-demand day. Adjust cutoff, packet requirements, or capacity based on actual return reasons. Keep emergency exceptions scarce and documented. Predictability comes from a routine people trust, not from extending the reviewer’s availability until every queue is empty.',
    headings: ['Define what enters the window', 'Protect the meaning of approval', 'Plan for limited review capacity', 'Close the queue honestly', 'Adjust from observed demand'],
  },
  {
    slug: 'philippines-editorial-qa-sampling-plan',
    title: 'An editorial QA sampling plan for Philippines content operations',
    excerpt: 'Choose article samples by risk and change, then record defects without turning a small review into a universal score.',
    opening: 'Reviewing every field on every article may be unrealistic once a publishing routine grows. Reviewing only the easiest articles is worse. An editorial QA sampling plan lets Philippines content operations inspect a defensible slice of work while remaining honest about what the sample cannot prove.',
    situation: 'Define the eligible population before selecting anything. Group articles by factors that could change defect risk: new contributor, new template, sensitive subject, unusual source, corrected route, or routine release. Choose a written selection rule and record why each item entered the sample. Convenience samples can still teach, but they should be labeled accurately.',
    ownerDecision: 'The editorial lead chooses risk strata, sample size, defect definitions, severity, and the action triggered by findings. Specialists decide substantive issues in their domain. A QA assistant applies the approved checks and documents evidence; they do not expand one observed error into a judgment about a writer, vendor, or national workforce.',
    assistantWork: 'A Philippines-based reviewer can inspect rendered routes, compare approved drafts, test canonicals and dates, trace material claims, check links, and record exact locations. They may fix routine presentation issues when authorized. Changes to meaning, service positioning, publication history, or regulated language go back to the accountable owner.',
    evidence: 'Build a finding from route, section, expected condition, observed condition, evidence, category, proposed severity, and reviewer. Use pass only when the sampled item met every defined check. Record not applicable separately. A vague quality percentage hides which controls failed and makes later reviewers unable to reproduce the result.',
    failure: 'Sampling breaks down when reviewers change criteria after seeing the article or select only items they suspect will fail. It also misleads when a clean sample is described as proof that the whole corpus is accurate. Keep the inference bounded. One severe defect may justify wider review, but the expansion should be a recorded owner decision.',
    example: 'A daily sample could include one article from a new template, one with an external statistic, one routine operating guide, and one route returned during approval. The reviewer checks the same defined fields, then explains differences by defect type. If the statistic lacks support, that finding may trigger a targeted check of other articles using the source.',
    measure: 'Report eligible count, sampled count, selection strata, defects by category, recheck results, and owner actions. Track recurring defects after a checklist or training change. Avoid comparing people when their samples contain different risk mixes. The useful question is whether a control catches and reduces a known failure pattern.',
    handoff: 'Return findings with screenshots or source excerpts where helpful, but always include the text location and expected correction. Separate fixes completed within authority from decisions awaiting an editor. After changes, retest the rendered route and close only the specific finding. Keep unresolved items in the sample record rather than lowering the denominator.',
    close: 'Revisit the plan when the content mix, template, staff, or risk changes. Drop checks that never apply only after confirming they are redundant, and add checks in response to real misses. Sampling should focus scarce review attention while preserving uncertainty, not manufacture a reassuring number for a dashboard.',
    headings: ['Define the population first', 'Select by visible risk', 'Record reproducible findings', 'Limit what the sample proves', 'Expand review deliberately'],
  },
  {
    slug: 'philippines-cms-staging-release-check',
    title: 'A CMS staging release check for a Philippines publishing assistant',
    excerpt: 'Compare the approved article with its staged route before release, including metadata, links, dates, and structured data.',
    opening: 'An approved draft can still become a broken page. Copying it into a CMS may drop headings, alter links, use the wrong date, or inherit metadata from another route. A staging release check gives a Philippines publishing assistant a bounded way to catch assembly defects before a page becomes public.',
    situation: 'Start with the approved version, intended canonical route, publication date, metadata, hero asset decision, and release owner. Open the staged page through the same routing layer readers will use when possible. Compare meaning and structure, not only visual similarity. Record the build or preview identity so a later change does not inherit the earlier pass.',
    ownerDecision: 'The publisher decides whether the article is approved, whether an observed difference is material, and when release occurs. Design owners decide template exceptions; subject owners decide changed claims. The assistant can report that staging differs from approval, but cannot resolve a disagreement by editing public meaning to fit the template.',
    assistantWork: 'The assistant can verify the H1, paragraphs, heading order, links, image and alt text, visible date, canonical, metadata, structured headline and datePublished, related links, and index card. They may correct authorized formatting mistakes. They should not change DNS, deployment settings, access policy, analytics, or unapproved copy as part of an article check.',
    evidence: 'Use a route-specific checklist with expected and observed values. Save exact URLs and timestamps, and capture a screenshot for visual defects. For metadata and structured data, record the relevant rendered markup rather than relying on a CMS field alone. The public or preview output is what the release check evaluates.',
    failure: 'A checklist can create false confidence when it is completed against the editor screen instead of the rendered route. Another failure is reusing a pass after the draft changes. Material edits, template updates, route changes, or a new build reopen the affected checks. The record should make that invalidation obvious.',
    example: 'Suppose the staged article visibly shows September 3 but its Article schema retains September 2 from copied data. The assistant records both values, identifies the source field, and returns the route for correction. They do not change the display date to make the two fields agree. After the owner-approved correction, the exact staged output is checked again.',
    measure: 'Track defects by assembly point: content transfer, route identity, metadata, structured data, assets, links, responsive presentation, and index exposure. Count how many were found before and after release. Avoid treating a low defect count as proof of thorough review; sample completed check records and deliberately test fields known to be copied between routes.',
    handoff: 'The release packet should identify the approved version, staged URL, checks passed, open findings, corrections made, final decision owner, and next action. If a required field cannot be verified, hold the route. A clear hold protects the publication record and gives the technical owner a narrow problem to solve.',
    close: 'Keep staging checks tied to observed failure modes. Automate deterministic comparisons where the repository supports them, then retain human reading for context and meaning. The routine is complete only when the checked output matches the approved article and the accountable publisher authorizes the release.',
    headings: ['Anchor the check to approval', 'Inspect the rendered route', 'Reopen checks after change', 'Separate assembly from judgment', 'Package the release decision'],
  },
  {
    slug: 'philippines-outsourced-editorial-voice-reference',
    title: 'Building an editorial voice reference for Philippines outsourced writers',
    excerpt: 'Create a usable voice reference from approved examples, reader needs, prohibited claims, and concrete editing choices.',
    opening: 'A voice guide that says professional, helpful, and engaging gives a writer almost nothing to act on. Those words describe aspirations, not sentence choices. An editorial voice reference for Philippines outsourced writers should show how the site explains work, addresses uncertainty, and separates useful guidance from unsupported promotion.',
    situation: 'Collect a small set of approved passages from the site and annotate why they work. Look at sentence length, vocabulary, directness, heading style, examples, calls to action, and how role boundaries are described. Include counterexamples that were rejected. The reference should reflect the company’s actual public material rather than an imagined national or corporate personality.',
    ownerDecision: 'The content owner decides brand position, reader relationship, prohibited promises, terminology, and when a specialist tone is required. Editors decide whether a draft matches those choices. A writer can identify patterns and propose alternatives, but should not invent a founder story, client result, credential, location, or cultural stereotype to make the voice feel distinctive.',
    assistantWork: 'A Philippines-based writer can apply approved examples, simplify inflated language, vary sentence rhythm, replace vague attribution with named evidence, and flag statements that need owner context. They can maintain a decision log when editors accept or reject recurring phrases. Public voice does not grant authority to decide business facts or testimonial claims.',
    evidence: 'For every rule, include an approved example, an explanation, and the kind of article where it applies. A research note may need neutral qualification; an operating guide can speak directly to a manager. Record the source route and approval date. Avoid copying long passages into every brief, which can make articles imitate structure instead of learning the underlying choice.',
    failure: 'Voice references fail when they become lists of fashionable words to add or ban without context. They also fail when every article uses the same opening, number of sections, example cadence, and conclusion. Consistency should help readers recognize judgment and boundaries, not make distinct topics sound mechanically interchangeable.',
    example: 'For a guide about inbox support, the reference might favor a plain statement such as the assistant can sort and draft while the owner approves sensitive replies. It would reject a sweeping promise about transforming communication. The first version names work and authority; the second claims an outcome without evidence. That contrast teaches more than an adjective list.',
    measure: 'Review editor corrections by category: unsupported promotion, vague actor, hidden uncertainty, repeated template, overlong setup, unclear boundary, or inconsistent terminology. Sample before and after passages. Do not score voice with a single automated percentage. Tools can surface patterns, but an editor must judge whether the prose serves the reader and preserves facts.',
    handoff: 'When returning a draft, cite the relevant reference example and explain the reader effect of the change. Distinguish mandatory factual or safety corrections from stylistic preference. Update the reference only after the owner accepts a durable rule. One editor comment on one unusual article should not silently become a universal standard.',
    close: 'Keep the reference short enough to consult while writing. Review it when the site’s services, audience, or approved terminology changes. Retire examples that no longer represent current material. A living voice reference should make judgment easier while leaving room for each article to find the structure its subject needs.',
    headings: ['Study approved prose', 'Turn taste into examples', 'Protect facts and boundaries', 'Avoid structural cloning', 'Learn from editor corrections'],
  },
  {
    slug: 'philippines-blog-performance-annotation-log',
    title: 'A Blog performance annotation log for a Philippines support team',
    excerpt: 'Explain traffic and engagement changes with dated operational context before recommending editorial action.',
    opening: 'A traffic chart rarely explains itself. A rise may follow a distribution change, a fall may coincide with broken tracking, and a flat line may hide that the article now serves a different query. A Blog performance annotation log helps a Philippines support team preserve context without turning correlation into a confident conclusion.',
    situation: 'Choose the smallest reporting unit that supports a decision: canonical article, content group, or campaign. Record the metric definition, source, date range, comparison period, filters, and known limitations. Then add dated events such as publication, material revision, index change, campaign link, tracking interruption, or source outage. Keep events separate from interpretations.',
    ownerDecision: 'The content or analytics owner decides metric definitions, comparison logic, materiality, and editorial response. A service owner approves commercial conclusions. An analyst can say that two events overlap in time, but causal language needs stronger evidence. The annotation log should make that limit visible rather than burying it in a dashboard footnote.',
    assistantWork: 'A Philippines-based assistant can export approved reports, reconcile route names, flag missing periods, add documented events, and prepare cautious observations. They should not fill data gaps with estimates, change attribution settings, declare that an article caused revenue, or rewrite a page solely because one short period declined.',
    evidence: 'Each annotation needs a date, event owner, source record, affected routes, and description limited to what is known. Each observation needs the query or report that produced it. Screenshots are useful but should not replace exported values or definitions. Preserve revisions so a later analyst can tell which context was available when a recommendation was made.',
    failure: 'The log becomes misleading when every fluctuation receives a story. It also becomes useless when annotations say updated content without naming what changed. Another common error is comparing unequal periods or mixing pageviews, users, clicks, and conversions as though they describe the same behavior. Define the question before selecting the number.',
    example: 'An article’s search clicks decline during the same week its title and internal links change. The assistant records both events and confirms the reporting period. The owner may wait for more observations, restore the prior title, or investigate query mix. The log supports those options, but it does not prove which change caused the decline.',
    measure: 'Track missing annotations discovered during review, unmatched route identities, data gaps, decisions supported by the log, and hypotheses later confirmed or rejected. Avoid rewarding the number of annotations. A quiet period may need none. Quality means that material operational events are traceable when someone asks why the chart changed.',
    handoff: 'A weekly note should state the observed movement, exact period, metric definition, relevant annotations, alternative explanations, and requested decision. Attach the underlying report. If tracking is uncertain, say that first and hold editorial recommendations that depend on it. A manager can then choose an investigation without mistaking prepared context for proof.',
    close: 'Review annotations alongside editorial and technical change records so the same event is not described differently in several systems. Archive stale hypotheses after recording the outcome. The log is most useful as institutional memory: it helps the next analyst avoid rediscovering context or repeating a confident explanation that the evidence never established.',
    headings: ['Define the observation', 'Record events without a story', 'Compare like periods', 'Offer bounded explanations', 'Preserve what later proved true'],
  },
  {
    slug: 'philippines-content-archive-decision-record',
    title: 'A content archive decision record for a Philippines editorial team',
    excerpt: 'Evaluate outdated articles through reader value, evidence risk, route history, and owner-approved disposition.',
    opening: 'Old content should not disappear because a spreadsheet labels it stale. An article may still answer a useful question, carry external links, or provide historical context. It may also contain guidance that no longer belongs in public. A content archive decision record helps a Philippines editorial team prepare evidence before an owner chooses to retain, revise, redirect, or remove a route.',
    situation: 'Create one record per canonical article. Capture the title, route, family, original publication date, last substantive review, current owner, purpose, important sources, internal links, known inbound value, and observed concern. State why the review began. Age alone is a weak reason; a changed claim, duplicate answer, broken reader path, or obsolete service boundary is more actionable.',
    ownerDecision: 'The publisher owns disposition and route behavior. Subject owners decide whether guidance remains accurate, technical owners approve redirects or removals, and service owners review commercial implications. An inventory assistant can prepare options but cannot erase publication history, merge articles, or assume that low measured traffic means no reader depends on the page.',
    assistantWork: 'A Philippines-based assistant can inspect the live route, compare current sources, map incoming and outgoing internal links, note duplicates, and assemble a before-and-after summary. They may correct inventory fields. They should not redate an article, replace its canonical, delete assets, or publish a rewritten version without explicit approval and a documented migration plan.',
    evidence: 'The record should show the observed problem and the evidence for each option. Retention may require no change or a scheduled review. Revision needs scoped claims and sources. Consolidation needs a target that genuinely answers the same reader question. Removal needs a plan for links and route response. Keep uncertainty visible, especially when analytics or backlink data are incomplete.',
    failure: 'Bulk cleanup fails when it treats routes as files rather than reader promises. Redirecting every old article to a general Blog page creates a working response but a poor destination. Quietly rewriting and changing the date creates false publication history. Another failure is preserving risky guidance solely because it once attracted traffic. The record must hold both value and harm in view.',
    example: 'Two articles may both discuss handoffs, yet one covers shift continuity and the other covers editorial approval. Similar vocabulary does not make them duplicates. The assistant compares questions, examples, links, and conclusions. The owner may keep both, narrow one, or consolidate only the overlapping section. The decision follows reader intent, not title similarity alone.',
    measure: 'Track records reviewed, decisions by disposition, unresolved owner questions, broken paths found, redirects retested, and repeated reasons for review. Do not call removed page count an improvement. Pair counts with examples and post-change checks. A smaller corpus can be easier to maintain, but only if readers still reach the appropriate answer.',
    handoff: 'Present the current condition, options, risk of each option, recommended next check, required owners, and decision deadline. After approval, record exactly what changed and verify the public route, canonical behavior, index, sitemap, and important internal links. Preserve the decision record even when the article is removed, because future editors need to know why.',
    close: 'Schedule archive review from evidence signals rather than an arbitrary purge. High-risk and frequently changed guidance deserves closer attention; stable operating explanations may remain useful for years. A careful record slows the deletion decision just enough to protect history, then makes the approved change easier to execute and verify.',
    headings: ['Start with the reader promise', 'Compare disposition options', 'Protect route history', 'Check the surrounding path', 'Verify the approved outcome'],
  },
  {
    slug: 'philippines-editorial-publishing-incident-review',
    title: 'Editorial publishing incident review for a Philippines content team',
    excerpt: 'Study wrong dates, routes, claims, links, or metadata through a factual timeline and controlled corrective actions.',
    opening: 'A publishing incident is not limited to a site outage. A wrong date, duplicate route, unsupported claim, broken canonical, or missing article can also harm the reader and the publication record. An incident review gives a Philippines content team a calm method for learning from the event after immediate correction is under control.',
    situation: 'Define the incident by observed reader impact and affected routes. Record when it began, how it was detected, what evidence confirmed it, who contained it, and when the public condition changed. Separate known facts from estimates. If the start time is uncertain, use a bounded range rather than inventing precision from the first report.',
    ownerDecision: 'The incident owner decides severity, containment, public communication, correction notice, rollback, and closure. Subject owners handle substantive claims; technical owners handle routing and release systems. A coordinator can assemble the timeline and verify fields, but should not make legal, privacy, customer, or reputational decisions on behalf of the accountable owner.',
    assistantWork: 'A Philippines-based coordinator can preserve screenshots and rendered markup, identify affected routes, compare approved and public versions, record actions, and maintain the decision log. They may perform pre-authorized reversible corrections. They should not delete evidence, rewrite timestamps, broaden the repair to unrelated pages, or deploy speculative changes because the queue is urgent.',
    evidence: 'Use source-system times in one stated time zone and link each event to a commit, approval, alert, screenshot, or route observation where available. Record competing accounts instead of forcing agreement. The timeline should distinguish detection, diagnosis, decision, change, and verification. Those moments answer different questions about how the control system behaved.',
    failure: 'Reviews fail when they search for a person to blame or begin with a favored cause. They also fail when the successful repair becomes proof that the cause is understood. A date correction may restore the page while leaving the copy workflow vulnerable. Ask which conditions allowed the error through and which existing check should have detected it.',
    example: 'Suppose twelve articles display the correct September 3 date but structured data says September 2. The coordinator confirms the affected routes, preserves output evidence, and traces the shared field. The owner approves a correction, all routes are rebuilt, and public markup is retested. The review then examines why visible and structured dates were checked separately or not at all.',
    measure: 'Useful observations include time to detection, time to containment, affected routes, reader-facing duration, correction returns, and whether agreed controls later caught a similar issue. Interpret these with incident complexity. Faster closure is not better if verification is skipped, and a long review may reflect an honest need for specialist evidence.',
    handoff: 'The closeout should list the confirmed condition, corrective action, public verification, remaining uncertainty, control change, owner, and review date. Keep longer-term improvements separate from immediate repair so the incident can close without losing follow-up work. Do not mark a recommendation complete simply because it appears in the review.',
    close: 'Share the practical lesson with the people who operate the relevant check, without exposing confidential details or turning the document into a cautionary story about an individual. Retest the changed control on an ordinary release. The value of the review appears in a clearer system and a reproducible check, not in the length of the report.',
    headings: ['Bound the incident', 'Build a factual timeline', 'Separate repair from cause', 'Change one accountable control', 'Retest on ordinary work'],
  },
];

const extensions: Record<string, { title: string; paragraphs: readonly string[] }> = {
  'philippines-content-assistant-morning-brief': {
    title: 'Run the first hour from the brief',
    paragraphs: [
      'The first working hour is a useful test of brief quality. The assistant should be able to confirm the route is unused, identify the primary reader question, open the permitted sources, and sketch the evidence order without sending a stream of basic questions. This does not mean uncertainty has disappeared. It means uncertainty is now specific. A question such as which company claim may be stated publicly belongs with an owner; a question such as whether a source contains a publication date belongs in routine research.',
      'Include a stop rule for apparent duplicates. Similar words do not automatically make two articles the same, but the assistant should compare the new thesis, intended reader decision, examples, section sequence, and conclusion with nearby routes. If the proposed article cannot be distinguished in those terms, return it to intake. Changing a few nouns or adding the current date does not create a new editorial identity.',
      'The brief should also identify the checks that occur after drafting. Name who reads for meaning, who confirms business boundaries, and who inspects the rendered route. When one person fills several roles, preserve the separate decisions. A single approved message should not become evidence that sources, metadata, canonical identity, and public output were all checked unless the record explicitly covers those conditions.',
      'Finally, protect the morning routine from becoming a surveillance exercise. Record work state and evidence, not constant presence. A contributor may spend part of the window reading, comparing, or waiting for a source. The useful management question is whether the next handoff is complete and within scope. Presence indicators do not answer that question, and they can distract from the quality of the article itself.',
    ],
  },
  'philippines-outsourced-source-freshness-watch': {
    title: 'Decide what a changed source means',
    paragraphs: [
      'Different changes require different responses. A corrected typo in a source may need no article action. A revised definition can affect the exact sentence that relied on it. A removed table may leave a citation inaccessible even if the historical statement remains accurate. Classify the change before opening a rewrite. The classification should describe reader risk and evidence status, not the amount of visual difference on the source page.',
      'Use an escalation threshold for sources that govern several articles. When one authoritative page supports multiple routes, a material change may justify a coordinated review. The researcher can produce an impact list, but each article still needs its own claim check. Do not apply a global replacement sentence without reading the local argument. The same source can play a central role in one article and provide incidental context in another.',
      'Keep a record when the decision is no change. State why the existing article remains supportable, who reviewed it, and when the question should return. This prevents the same alert from being rediscovered every week. It also helps a later editor see that the older retrieval date was considered rather than overlooked.',
      'When a replacement source is necessary, compare authority, scope, period, and terminology. A newer page is not automatically a better match. The new evidence must support the public proposition actually written. If no suitable replacement exists, narrowing or removing the claim is more honest than attaching a nearby link that gives the appearance of support.',
    ],
  },
  'philippines-editorial-backlog-capacity-board': {
    title: 'Use the board during a constrained day',
    paragraphs: [
      'Begin the day by checking entry conditions rather than asking everyone for a status paragraph. Cards that have the required artifact can move; cards missing it stay put with a reason. This keeps the discussion about observable work. It also reveals when the board’s own fields are insufficient, because people repeatedly need information that the current state does not capture.',
      'Set a work-in-progress limit where attention is scarce. If evidence review can accept three articles, placing seven there does not create capacity. Keep the other four in a truthful preceding state and show the order proposed by the lead. Contributors can prepare approved supporting work, but the board should not imply that a reviewer has accepted responsibility for material they have not received.',
      'Aging needs context. An article waiting two days for a specialist may be healthier than an article rewritten three times within a day because its brief was unclear. Review age alongside hold reason, business importance, and permitted next work. The board should help a manager decide, not turn one duration into a universal alarm.',
      'At weekly review, look for recurring transfers that add no information. If articles bounce between drafting and review for the same missing source field, repair the entry rule. If the owner-decision column grows, assign review windows or backups. Change one operating rule at a time and observe the next cycle before redesigning the entire workflow.',
    ],
  },
  'philippines-virtual-assistant-internal-link-review': {
    title: 'Judge links in the finished reading path',
    paragraphs: [
      'Read the source article once without clicking. Note where a reader may need definition, evidence, or an operational next step. Then inspect the existing links. This order reduces the temptation to justify links simply because they are already present. It also surfaces places where plain explanation would serve better than sending the reader to another page.',
      'Anchor text should set a fair expectation. Generic phrases such as learn more make scanning harder, while exaggerated labels can misrepresent a modest destination. Use concise language that names the topic or action available on the next page. Do not cram keywords into an otherwise natural sentence. The link exists for navigation and context, not to make the paragraph sound optimized.',
      'Check circular and competing paths across a small topic cluster. If three articles all present themselves as the next step, the reader may never reach the service or explanation that resolves the original question. Map the sequence and let the owner decide which route is primary. The assistant can show the loop with evidence without choosing the site hierarchy alone.',
      'After edits, test keyboard access and the visible focus state as part of the rendered review. Confirm that external behavior was not introduced accidentally and that the target does not redirect to an unrelated page. Record the final source and destination together. Link maintenance is complete only when both ends of the path remain meaningful.',
    ],
  },
  'philippines-outsourced-subject-matter-question-routing': {
    title: 'Make expert time easier to use',
    paragraphs: [
      'Maintain a routing directory by subject and decision type, not merely job title. The person who can explain a process may differ from the person authorized to approve public wording. Include a backup and the conditions under which a question should wait rather than move to someone outside the domain. Review the directory when roles or services change.',
      'Prepare answer options only when they clarify the decision. Each option should state its evidence and consequence. Do not use a forced choice when the honest answer may be neither, more research needed, or outside our scope. Experts should be able to correct the premise. A narrow packet saves time without narrowing reality to the writer’s preferred outcome.',
      'Set priority from reader and business risk. A cosmetic terminology preference should not displace a question about whether a public claim is accurate. The coordinator can label the categories using approved rules and flag deadline impact. The expert or editorial lead still owns reprioritization when several material questions compete.',
      'Once answered, check every place in the draft that depended on the question. A decision may affect the headline, example, conclusion, metadata, or related link, not only the highlighted sentence. Return a short impact checklist with the revised version. This prevents a correct expert answer from being applied partially while contradictory language survives elsewhere.',
    ],
  },
  'philippines-content-approval-service-window': {
    title: 'Protect the queue between windows',
    paragraphs: [
      'Requests arriving after cutoff need a predictable home. Record them for the next window with a completeness result and expected reviewer. Do not keep pinging an owner through several channels. A true urgent exception should name the risk, why the ordinary window is insufficient, who authorized priority, and which scheduled work may move as a consequence.',
      'Use distinct response labels and require a note where needed. Approved means the identified version can proceed within the stated scope. Returned means a correction is required before a new decision. Held means the reviewer lacks evidence, authority, or capacity. Cancelled means the commissioning owner no longer wants the route. These labels prevent conversational replies from acquiring more authority than intended.',
      'When a reviewer delegates temporarily, record the domain and duration of that delegation. A backup who can approve routine editorial fit may still be unable to approve a specialist claim. The coordinator should split the packet if some parts can move and one part must wait. Partial decisions are useful when their boundaries remain explicit.',
      'Audit a small set of approvals against the released articles. Confirm that the version, claims, route, and date match what the owner accepted. If later edits changed meaning, treat them as a new decision rather than stretching the earlier approval. This check protects the reviewer as well as the publication record.',
    ],
  },
  'philippines-editorial-qa-sampling-plan': {
    title: 'Turn findings into a controlled response',
    paragraphs: [
      'Before sampling begins, write what happens after each severity. A presentation defect may enter a routine correction queue. An unsupported material claim may require a hold and wider review. A route collision may require technical and editorial owners. Predefined responses reduce the chance that a reviewer inflates or minimizes a finding to obtain a preferred outcome.',
      'Calibrate reviewers with the same few examples. Ask each person to apply the checklist independently, compare differences, and clarify the rule. Preserve legitimate judgment instead of forcing artificial agreement. The objective is consistent evidence and escalation, not identical prose preferences. Recalibrate after a template or policy changes.',
      'Rechecks should inspect the correction and nearby risk. Fixing a canonical can affect metadata or sitemap output; changing a claim can leave the summary inconsistent. Keep the recheck bounded enough to finish but broad enough to catch the direct consequence of the edit. Record who performed it and which rendered version they saw.',
      'Close the sampling period with an owner decision. Continue the current control, revise a check, expand a targeted review, or accept a documented residual risk. A report without a decision leaves findings to age in a separate queue. The QA role prepares evidence; the accountable lead decides what the operating system does next.',
    ],
  },
  'philippines-cms-staging-release-check': {
    title: 'Check details that previews often hide',
    paragraphs: [
      'Inspect the page source or rendered metadata for fields that may not appear in the visual preview. Confirm the canonical uses the production domain and exact slug, Article schema uses the intended date, and the structured headline matches the article identity. Check that test or preview addresses do not leak into share metadata. Record literal values rather than a general metadata pass.',
      'Test links by purpose. Internal navigation should reach the expected route, evidence links should support the surrounding statement, and calls to action should point to the owner-approved destination. Do not submit forms while checking a content release. A safe review can verify the action and endpoint without creating a lead or customer record.',
      'Read the page at a narrow viewport and with images unavailable. The article should remain understandable, headings should follow a useful order, and alt text should describe the editorial purpose of an informative image. If no approved unique image exists, follow the campaign’s stated fallback rather than choosing uncertain stock material to fill space.',
      'Make the final decision from one immutable candidate when the tooling permits it. If a new commit or build appears before release, determine whether it touches the route or shared rendering. Recheck affected conditions. This prevents a valid preview from becoming a blanket approval for later output with a different identity.',
    ],
  },
  'philippines-outsourced-editorial-voice-reference': {
    title: 'Edit a draft with the reference',
    paragraphs: [
      'Start with meaning. Identify the reader’s problem, the evidence available, and the decision the article helps them make. Only then review voice. This order prevents a pleasant sentence from concealing a weak claim. It also stops editors from spending time on rhythm before they know whether the section belongs.',
      'Watch for language that gives an unnamed group an opinion, declares ordinary work transformative, or adds significance without evidence. Replace it with the actor and action when known. If the source does not support the detail, remove it or route a question. Plain prose is not a loss of authority; unsupported confidence is.',
      'Vary structure according to the topic. A troubleshooting article may follow symptoms and decisions. A planning guide may move from scope to handoff. A review article may organize evidence by risk. The voice reference can keep terminology and boundaries consistent while each subject determines its own sequence and examples.',
      'Finish with a human reading pass. Remove repeated transitions, mechanical groups of three, copied conclusion patterns, and sentences that merely announce importance. Read aloud when useful. Confirm that punctuation, quotation style, and headings match the site. The final copy should sound like an editor made choices, not like a checklist assembled every paragraph.',
    ],
  },
  'philippines-blog-performance-annotation-log': {
    title: 'Review a metric change without overclaiming',
    paragraphs: [
      'Begin with data integrity. Check whether collection, consent behavior, tagging, route identity, reporting filters, or timezone changed during the comparison. A clean-looking chart can combine incompatible conditions. If the data pipeline is uncertain, investigate it before asking writers to revise an article based on the apparent result.',
      'Use more than one relevant observation when the decision warrants it. Search impressions and clicks describe a different stage from on-page reading or a completed business action. They may move in opposite directions. State which part of the reader path each metric describes and avoid combining them into a single success label.',
      'Set a review horizon appropriate to the question. A newly published article may have too little exposure for stable interpretation; an established route may deserve attention after a sustained change or a known event. Record why the selected window is useful. Do not wait for arbitrary certainty, but do not turn one unusual day into strategy.',
      'When the owner approves an experiment, state the exact change, hypothesis, protected conditions, start date, and review date. Avoid changing headline, structure, internal links, and call to action together if the team wants to learn which choice mattered. Preserve the prior version and report inconclusive results honestly.',
    ],
  },
  'philippines-content-archive-decision-record': {
    title: 'Carry out the chosen disposition safely',
    paragraphs: [
      'For a revision, create a bounded brief that names the claims and reader paths under review. Preserve the original publication date unless the site’s documented policy supports another treatment, and use a truthful modified date where appropriate. A refresh is not a newly created article merely because substantial editing occurred.',
      'For consolidation, map every useful section and incoming internal link to the proposed destination. Confirm that the destination can satisfy the original reader question without a confusing jump. Record which material will be retained, rewritten with evidence, or omitted. The owner should approve the combined thesis before implementation begins.',
      'For removal, decide the route response from reader intent and technical policy. A relevant replacement may justify a redirect. No replacement may justify a clear unavailable response and repaired internal links. Sending every removed route to the homepage hides the decision and can strand readers. Verify external behavior without promising control over third-party links.',
      'After any disposition, sample search results, navigation, related links, and the sitemap after the normal update interval. Keep the article in the decision inventory until these checks pass. Closure means the intended public path works and the historical decision is recorded, not simply that a source file changed.',
    ],
  },
  'philippines-editorial-publishing-incident-review': {
    title: 'Follow corrective work after the meeting',
    paragraphs: [
      'Assign every corrective action one owner, concrete deliverable, due condition, and verification method. Avoid broad actions such as improve communication. A useful action might require the release checklist to compare visible and structured dates from the same rendered page. The verification should demonstrate that behavior on a later ordinary route.',
      'Separate prevention from detection. Some errors can be blocked before release; others are better found quickly through a post-release check. Trying to prevent every conceivable issue can make the publishing system unusable. The incident owner should choose controls in proportion to reader harm, recurrence, and the reliability of the proposed check.',
      'Review whether workload or timing contributed without assuming they caused the event. A crowded queue may expose a weak copy step, but adding more time will not necessarily repair it. Look for evidence in handoffs, skipped states, and competing versions. Preserve the difference between a contextual condition and a confirmed cause.',
      'At the follow-up date, inspect the actual corrective artifact and test result. Close actions that meet their condition, revise those that proved impractical, and retain an owner for unresolved risk. Do not keep the entire incident open solely because a broad aspiration remains. Close the event with honesty while governing longer improvements through normal work.',
    ],
  },
};

function body(t: Topic): readonly string[] {
  return [t.opening, t.situation, t.ownerDecision, t.assistantWork, t.evidence, t.failure, t.example, t.measure, t.handoff, t.close, ...extensions[t.slug].paragraphs];
}

function sections(t: Topic) {
  const paragraphs = body(t);
  const core = t.headings.map((title, index) => ({
    title,
    paragraphs: paragraphs.slice(index * 2, index * 2 + 2),
    checks: index === 0
      ? ['Is the work unit explicit?', 'What evidence starts the task?', 'Who accepts the result?']
      : index === 4
        ? ['What remains unresolved?', 'Who owns the next decision?', 'How will the public result be verified?']
        : ['What was directly observed?', 'Which action stays within the role?', 'Where is the decision recorded?'],
  }));
  return [...core, { title: extensions[t.slug].title, paragraphs: extensions[t.slug].paragraphs, checks: ['What evidence supports the decision?', 'Which boundary protects the role?', 'What condition closes the work?'] }];
}

export const sep3BlogPosts = topics.map((topic) => ({
  slug: topic.slug,
  title: topic.title,
  excerpt: topic.excerpt,
  minutes: 9,
  publishedAt,
}));

export const sep3BlogBasics = Object.fromEntries(topics.map((topic) => [topic.slug, {
  intro: topic.opening,
  sections: sections(topic),
}]));
