type Topic={slug:string;title:string;excerpt:string;lane:string;record:string;owner:string};
const publishedAt='2026-09-09';
const topics:readonly Topic[]=[
{slug:'philippines-customer-support-macro-retirement-log',title:'When should a support macro be retired?',excerpt:'A practical review lane for outdated customer replies, with policy decisions kept with the client.',lane:'customer-support macro library',record:'reply version, policy link, last review, usage count, exception notes, and replacement status',owner:'support policy owner'},
{slug:'philippines-executive-assistant-meeting-brief',title:'The five-minute meeting brief an executive will actually read',excerpt:'Turn scattered calendar and document context into a compact, sourced pre-meeting note.',lane:'executive meeting preparation',record:'meeting purpose, participants, time zone, decision needed, source links, open questions, and sensitivities',owner:'executive or meeting owner'},
{slug:'philippines-ecommerce-backorder-customer-update',title:'A calmer way to manage backorder updates',excerpt:'Give ecommerce support a repeatable update routine without inventing delivery promises.',lane:'ecommerce backorder queue',record:'order, item, supplier status, last verified date, approved options, customer contact, and next check',owner:'inventory and customer-policy owners'},
{slug:'philippines-bookkeeping-receipt-matching-queue',title:'How to keep a receipt-matching queue from becoming a junk drawer',excerpt:'Organize unmatched receipts so bookkeeping support can resolve facts and escalate accounting questions.',lane:'receipt-matching queue',record:'entity, transaction, amount, date, source, proposed match, evidence, conflict, and review state',owner:'authorized accounting owner'},
{slug:'philippines-recruitment-interview-scheduling-buffer',title:'Interview scheduling needs a buffer, not more chasing',excerpt:'Build a candidate scheduling routine that accounts for time zones, preparation, and changes.',lane:'candidate interview calendar',record:'candidate consent, panel availability, time zones, format, access needs, buffer, confirmation, and change history',owner:'recruiting lead'},
{slug:'philippines-real-estate-lease-document-index',title:'A lease document index that answers “which version?”',excerpt:'Help real estate administrators keep executed files, amendments, and notices findable without legal interpretation.',lane:'lease document library',record:'property, party, document type, effective date, execution state, version, secure link, and retention rule',owner:'property manager or counsel'},
{slug:'philippines-healthcare-admin-referral-status-board',title:'Make referral status visible without making a clinical call',excerpt:'A bounded healthcare administration board for tracking documents, acknowledgments, and owner actions.',lane:'referral administration queue',record:'approved identifier, referral source, destination, received state, missing items, consent state, and next owner',owner:'authorized clinical or referral owner'},
{slug:'philippines-sales-operations-quote-expiry-check',title:'The quote-expiry check that prevents awkward follow-ups',excerpt:'Keep quote validity, approvals, and CRM tasks aligned before sales outreach resumes.',lane:'sales quote follow-up queue',record:'quote identifier, version, expiry, pricing approval, customer status, owner, contact restriction, and next action',owner:'sales or pricing owner'},
{slug:'philippines-legal-admin-matter-intake-gap-list',title:'Turn incomplete matter intake into a precise gap list',excerpt:'Structure missing legal intake records while lawyers retain conflict, deadline, and legal judgments.',lane:'legal matter intake',record:'matter reference, approved party names, document checklist, source, received state, conflict-check state, and owner',owner:'supervising lawyer'},
{slug:'philippines-marketing-content-approval-clock',title:'Stop losing launch time in the content approval gap',excerpt:'Track what is waiting for review, what changed, and who can authorize publication.',lane:'marketing content approval queue',record:'asset, channel, version, claims evidence, reviewer, requested date, decision, revisions, and release state',owner:'campaign and brand owner'},
{slug:'philippines-it-helpdesk-device-return-handoff',title:'A device-return handoff that does not end at “shipped”',excerpt:'Follow equipment from offboarding request through receipt and verified inventory update.',lane:'offboarding device-return queue',record:'assigned device, condition note, authorization, carrier reference, custody events, receipt, and inventory verification',owner:'IT asset or security owner'},
{slug:'philippines-operations-recurring-task-sunset-review',title:'Some recurring tasks should be allowed to end',excerpt:'A monthly review for retiring reports and routines that no longer have a decision or reader.',lane:'recurring operations register',record:'task purpose, requester, consumer, cadence, effort, last use, dependencies, control value, and proposed disposition',owner:'process owner'},
];
export const sep9BlogPosts=topics.map(t=>({slug:t.slug,title:t.title,excerpt:t.excerpt,minutes:8,publishedAt,heroImage:'/research-batch-thumbnail.jpg'}));
export const sep9BlogBasics=Object.fromEntries(topics.map(t=>[t.slug,{intro:`A Philippines-based specialist can keep the ${t.lane} moving when the record is precise and the decision boundary is visible. The routine below favors verified state over confident guesses.`,sections:[{title:'Build the working record',paragraphs:[`Keep one controlled record containing ${t.record}. Link to source systems instead of copying restricted information into chat.`,`Define the population and cutoff before work begins. A blank field means unknown or not yet received; it should never be silently converted into a convenient answer.`],checks:['What is the source of truth?','Which cutoff applies?','What information is still missing?']},{title:'Separate preparation from authority',paragraphs:[`The Philippines specialist may gather permitted evidence, reconcile identifiers, prepare updates, and route exceptions. Decisions reserved for the ${t.owner} stay there.`,`Write the escalation trigger and expected response into the workflow. If records conflict, preserve both observations and their timestamps rather than choosing one without approval.`],checks:['Which actions are pre-authorized?','Who decides an exception?','Are conflicts visible?']},{title:'Close on observable evidence',paragraphs:[`A sent message or checked box is not completion. Verify the resulting system state, record the reviewer and time, and leave rejected, returned, or pending work visible.`,`Review age, rework, and missing-source patterns with counts and denominators. Those measures describe this ${t.lane}; they do not prove individual performance or business impact.`],checks:['What proves completion?','Was the owner notified?','Are limitations stated?']}]}]));
