type Post = {
  slug:string; title:string; excerpt:string; published:string; statistic:string; methodology:string;
  body:readonly string[]; dataSections:readonly {heading:string;text:string}[];
  faqs:readonly {question:string;answer:string}[]; sources:readonly string[]; related:readonly string[]; hero:string;
};

const sources = ['https://psa.gov.ph/content/2020-census-population-and-housing-results','https://www.ilo.org/data','https://data.worldbank.org/indicator/IT.NET.USER.ZS?locations=PH','https://www.oecd.org/en/data.html'];
const tail = (topic:string, boundary:string) => [
  `The Philippines context is useful only when it sharpens a role question. Public datasets describe populations, systems, or indicators; they do not describe the quality of one Outsourced Philippines work lane. A manager should therefore write down the unit being observed, the period, the source definition, and the decision that the evidence may inform. This protects the research from becoming a country-level promise.`,
  `For ${topic}, the first test should use real but appropriately minimized examples. Include an ordinary item, an incomplete item, and an exception that requires escalation. Record what the specialist was asked to do, what evidence was available, what changed, and what the reviewer accepted. A small sample is directional. It becomes more useful when correction reasons are retained rather than collapsed into a pass or fail score.`,
  `A useful operating record separates source fact, work performed, interpretation, and owner decision. That separation matters in Philippines-based staffing because a support specialist may prepare evidence while a client retains authority over money, policy, legal, clinical, employment, security, or customer-treatment decisions. The handoff should make that boundary visible instead of relying on an informal conversation.`,
  `Measurement should pair quality with time. Track first-pass acceptance, correction category, unresolved-item age, source freshness, and escalation timeliness with denominators and observation dates. Do not treat volume as quality or a short cycle as proof of accuracy. If the queue is paused because an owner or source is unavailable, record the pause rather than counting the item as complete.`,
  `Access design is part of the evidence. Identify the systems and fields needed for ${topic}, then remove fields that are not required for the defined output. Individual accounts, least-necessary permissions, and an audit trail for material changes make review possible. Public research cannot establish legal compliance for a client workflow; contracts, policy, and applicable professional obligations still govern the actual work.`,
  `The most important exception is often the one that exposes a weak definition. If two reviewers disagree, preserve both readings, compare the written acceptance rule, and revise the rule before expanding the lane. If a source conflicts with another source, route the conflict to the owner instead of choosing the version that makes the queue look cleaner. This is operational evidence, not a test of personal loyalty or effort.`,
  `Continuity requires a safe pause condition and a fallback record. A distributed Philippines-based team should know what to do when a tool is unavailable, a request changes scope, or a decision owner cannot respond. The fallback should contain only the minimum necessary context, a next owner, and a resume condition. This turns interruption into a visible state rather than hidden rework.`,
  `The evidence does not prove that outsourcing will produce a particular revenue, savings, compliance, or service result. It supports a narrower inference: a clearly bounded lane is easier to train, sample, review, and improve than a role described only by a broad outcome. Outsourced Philippines can use that inference to frame a staffing conversation around tasks, tools, hours, review, and boundaries.`,
  `Limitations are material. PSA, ILO, World Bank, and OECD resources use different populations, dates, units, and methods. Some are revised; some describe context rather than performance; none can establish the fit of an individual specialist or the readiness of a client’s instructions. A responsible conclusion carries those limits beside the finding and identifies what direct evidence is still needed.`,
  `The evidence-led decision is to pilot ${topic} as a narrow support lane, define its finish line, expose its exceptions, and review a dated sample before granting more responsibility. Keep ${boundary} with the authorized owner. Expand only when another reviewer can reproduce the result from the same source records and when normal, incomplete, and exceptional work are all visible.`,
];

const make = (slug:string,title:string,excerpt:string,statistic:string,question:string,topic:string,boundary:string,hero:string,extra:string,published:string):Post => ({
  slug,title,excerpt,published,statistic,
  methodology:`This desk review compares official Philippine and international public data with a bounded operating hypothesis about ${topic}. It does not pool unlike datasets or estimate a market-wide effect. Facts are kept separate from analysis: sources establish definitions and context, while the proposed queue, sample, and decision rule are analytical tests for an Outsourced Philippines staffing lane.`,
  body:[`Research question: ${question}`,`Evidence scope: ${statistic} This fact provides context, not a prediction about one worker, vendor, or client. The review uses source definitions, reference periods, and stated limitations rather than treating a headline number as a service benchmark.`,extra,...tail(topic,boundary)],
  dataSections:[{heading:'Facts and analysis',text:`The cited sources support the factual context and definitions. The operational recommendation for ${topic} is analysis: it should be tested against current records, a named reviewer, and an agreed acceptance rule.`},{heading:'Evidence boundary',text:`A support specialist may prepare, classify, reconcile, research, or route evidence within ${topic}. ${boundary} The record should show where preparation ends and owner judgment begins.`}],
  faqs:[{question:'What should a buyer test first?',answer:`Test one representative batch for ${topic}, including ordinary work, missing evidence, and an exception. Record acceptance, correction reasons, and the owner’s feedback.`},{question:'Do public indicators predict individual performance?',answer:'No. They provide context only; role-specific evidence and accountable review are required.'}],
  sources,related:['philippines-bpo-workforce-research','philippines-document-control-research'],hero
});

export const aug20ResearchPosts:readonly Post[] = [
  make('philippines-outsourcing-handoff-evidence-research','Philippines Outsourcing Handoffs: What Evidence Makes a Work Transfer Reproducible?','A handoff is reviewable when the next owner can reconstruct the source, action, unresolved question, and resume condition.','ILO and World Bank data catalogues illustrate why a claim needs a defined population, period, and metadata before it is compared.','Can a Philippines-based handoff remain reliable when the original worker and the next owner do not share the same conversation?','handoff evidence across Philippines-based staffing operations','approval, policy, and exception decisions','/aug20-research-heroes/aug20-handoff-records.png','The practical test is not whether a note exists. It is whether an authorized reviewer can reproduce the state of the item without asking the original worker to explain missing context. A handoff needs the source link or record identifier, the action taken, the fields changed, the unresolved question, the next owner, and the condition that permits work to resume.','2026-08-20'),
  make('philippines-outsourcing-invoice-reconciliation-research','Philippines Outsourcing Invoice Reconciliation: Where Should Evidence Stop Before Approval?','Invoice support can organize source records and unmatched items without turning reconciliation into financial authorization.','BSP payment-system publications use explicit transaction definitions and periods, a useful model for separating payment evidence from an account-level decision.','Which invoice-reconciliation tasks can a Philippines-based support lane perform without owning approval, settlement, or dispute judgment?','invoice reconciliation for Philippines-based finance support','payment approval, credits, write-offs, and disputes','/aug20-research-heroes/aug20-invoice-reconciliation.png','An invoice queue becomes analytically useful when it distinguishes received, duplicate, matched, unmatched, disputed, pending-owner-review, and approved states. Matching fields can be checked against an approved source, but a support worker should not infer that a discrepancy is immaterial or authorize payment because the amount appears familiar. The research question is therefore about evidence sufficiency, not about delegating financial authority.','2026-08-20'),
  make('philippines-outsourcing-knowledge-transfer-research','Philippines Outsourcing Knowledge Transfer: What Makes a New Work Lane Learnable?','Knowledge transfer is measurable through examples, feedback timing, access boundaries, and the first reviewed batch—not a generic onboarding promise.','The PSA labor-force programme and ILO data resources show why population context needs definitions and periods before interpretation.','What evidence shows that a Philippines-based specialist has received enough context to begin a bounded support lane safely?','knowledge transfer for Philippines-based operations roles','employment, performance, and access decisions','/aug20-research-heroes/aug20-knowledge-transfer.png','A transfer record should show the approved task, one accepted example, one rejected or exceptional example, the permitted systems, the reviewer, the feedback deadline, and the point at which the specialist must pause. A slide deck or meeting attendance alone cannot establish that the work definition was understood. The first batch is evidence about the task design as much as it is evidence about execution.','2026-08-20'),
  make('philippines-outsourcing-customer-feedback-evidence-research','Philippines Outsourcing Customer Feedback Analysis: When Is a Theme More Than an Anecdote?','Feedback support is more defensible when the sampling frame, coding rule, source trail, and escalation state remain visible.','PSA public datasets demonstrate why a sample needs a defined population and period before a conclusion is generalized.','How can a Philippines-based feedback analyst distinguish a documented customer signal from a prevalence claim or product decision?','customer feedback analysis in Philippines-based support operations','customer treatment, product priority, and remediation commitments','/aug20-research-heroes/aug20-feedback-analysis.png','A feedback record should preserve the channel, collection period, cohort or sampling rule, duplicate treatment, exact source reference, coding decision, and uncertainty. One comment is evidence of one reported experience. It may justify routing or closer review, but it does not establish how common the experience is or which product change should be prioritized. Coding disagreement is itself evidence about the taxonomy.','2026-08-20'),
  make('philippines-outsourcing-vendor-records-research','Philippines Outsourcing Vendor Records: Can Document Readiness Be Measured Without Certifying Compliance?','Vendor-record support can track documents, dates, and exceptions while compliance conclusions remain with the authorized owner.','OECD and ILO data resources show why comparable evidence needs clear definitions, dates, and metadata rather than a folder count.','What can a Philippines-based vendor-record lane prove about document readiness, and what must it leave undecided?','vendor document records for Philippines-based operations support','supplier approval, legal interpretation, and compliance certification','/aug20-research-heroes/aug20-vendor-records.png','A document register should distinguish requested, received, expired, contradictory, under review, and accepted-by-owner states. It should retain issuer, scope, source location, received date, and review date without implying that a complete folder is a certification. The analytical value lies in showing where evidence is missing or stale and who has authority to decide whether the requirement has been satisfied.','2026-08-20')
];
