import type {ResearchPost} from './sep28-research-batch';
const published='2026-10-08' as const,hero='/research-batch-thumbnail.jpg' as const;
const sources=['https://www.gao.gov/greenbook','https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final','https://www.nist.gov/privacy-framework','https://www.archives.gov/records-mgmt'] as const;
type BlogSpec={slug:string;title:string;excerpt:string;work:string;owner:string;decision:string};
const blogSpecs:BlogSpec[]=[
 {slug:'philippines-service-queue-owner-conflict',title:'Resolve a Service Queue Owner Conflict with Philippines-Based Support',excerpt:'Preserve assignment evidence and route a current-owner decision without letting a case disappear between teams.',work:'a service case that shows two active owners',owner:'the queue manager and business process owner',decision:'which owner is accountable now and how the conflicting assignment should be corrected'},
 {slug:'philippines-timezone-handoff-acceptance',title:'Prove Cross-Timezone Handoff Acceptance in a Philippines Support Lane',excerpt:'Connect sent, received, acknowledged, and first-action evidence across shifts without treating delivery as acceptance.',work:'a cross-timezone handoff with no attributable acceptance event',owner:'the outgoing and incoming service owners',decision:'whether responsibility transferred and which open items need renewed acknowledgement'},
 {slug:'philippines-virtual-assistant-access-request-evidence',title:'Build Access-Request Evidence for a Philippines Virtual Assistant',excerpt:'Request the minimum role needed for defined work while preserving approval, expiry, and verification evidence.',work:'a recurring task blocked by missing or excessive access',owner:'the system, security, and service owners',decision:'whether to provision, narrow, reassign, or stop the access request'},
 {slug:'philippines-customer-update-source-version',title:'Review a Customer Update Source-Version Conflict',excerpt:'Compare the source, draft, approval, and later change before a Philippines support specialist sends a stale promise.',work:'a customer update whose source changed after drafting',owner:'the customer communication and source-system owners',decision:'which source version supports the update and whether renewed approval is required'},
 {slug:'philippines-ecommerce-catalog-effective-time',title:'Control Ecommerce Catalog Effective Times with Philippines Operations Support',excerpt:'Keep requested, approved, scheduled, and published times separate when product changes cross timezones.',work:'an ecommerce catalog change whose effective time differs across systems',owner:'the catalog, pricing, and publication owners',decision:'which approved value becomes effective and when'},
 {slug:'philippines-interview-panel-change-handoff',title:'Handle an Interview Panel Change with Philippines Recruiting Support',excerpt:'Preserve candidate communication, availability, panel authority, and accommodation routing through a late change.',work:'an interview whose panel or schedule changes after candidate confirmation',owner:'the recruiter, hiring manager, and accommodations owner',decision:'which panel and schedule remain authorized and what must be reconfirmed'},
 {slug:'philippines-executive-calendar-delegate-conflict',title:'Resolve an Executive Calendar Delegate Conflict',excerpt:'Trace delegate scope, event ownership, and competing instructions without guessing which request outranks another.',work:'an executive calendar event changed by delegates with conflicting instructions',owner:'the executive and calendar administration owner',decision:'which instruction controls and whether affected attendees need an approved correction'},
 {slug:'philippines-vendor-record-identity-mismatch',title:'Review a Vendor Record Identity Mismatch with Philippines Support',excerpt:'Compare legal entity, vendor account, tax, contact, and payment references while keeping acceptance decisions with owners.',work:'a vendor record whose legal identity does not align across sources',owner:'vendor-master, finance, tax, and compliance owners',decision:'whether the records describe one approved vendor and which fields require correction'},
 {slug:'philippines-weekly-report-denominator-drift',title:'Detect Denominator Drift in a Weekly Philippines Operations Report',excerpt:'Tie every rate to its current definition, population, exclusions, and source before publishing a misleading trend.',work:'a weekly metric whose denominator or exclusion rule changed',owner:'the reporting and business metric owners',decision:'which definition applies and how the comparability break should be disclosed'},
 {slug:'philippines-customer-escalation-recipient-identity',title:'Verify Recipient Identity Before a Customer Escalation',excerpt:'Confirm the authorized recipient and minimum necessary case context before sensitive information leaves the routine queue.',work:'a sensitive escalation addressed to an uncertain recipient identity',owner:'service, privacy, and security owners',decision:'which verified recipient may receive the minimum necessary information'},
 {slug:'philippines-content-asset-rights-expiry',title:'Review Expiring Content Asset Rights with Philippines Marketing Support',excerpt:'Connect asset source, license scope, approval, publication locations, and removal evidence before rights expire.',work:'a published content asset whose license or approval window is ending',owner:'marketing, brand, legal, and content owners',decision:'whether the asset remains authorized, requires replacement, or must be removed'},
 {slug:'philippines-offboarding-automation-ownership',title:'Transfer Automation Ownership During Philippines Staff Offboarding',excerpt:'Inventory scheduled jobs, integrations, tokens, alerts, and saved templates before removing a departing user.',work:'automations and reusable artifacts owned by a departing support specialist',owner:'system, security, and business process owners',decision:'which artifacts remain valid, require reassignment, or must be disabled'}
];
const common=(s:BlogSpec)=>[
 `A Philippines-based support lane becomes unreliable when ${s.work} is handled through memory or private chat. Open one controlled case and record the company entity, customer or record identifier, queue, channel, dates, current status, and exact unresolved question. Preserve the source before refreshing, editing, forwarding, or correcting it. A screenshot can support review, but a native record, export, version, or event identifier is stronger. The first objective is not to make the case look clean. It is to retain what the specialist actually received and what each system showed at that moment.`,
 `State the authority boundary at intake. ${s.owner} must decide ${s.decision}. Support may gather sources, normalize fields, prepare a chronology, draft a bounded update, and route the question. It should not invent approval, change policy, remove a control hold, broaden access, reveal sensitive information, or promise an outcome. Naming the owner and decision early keeps administrative preparation from silently turning into business authority and gives the next shift a reliable stopping point.`,
 `Build a source register for every document, message, system record, policy, checklist, approval, and report. Record location, owner, identifier, version, retrieval time, effective time, and permitted use. Keep original values beside normalized values. Similar names, totals, subject lines, or record labels are comparison signals, not proof that two records describe the same party or event. Mark evidence received from an unverified person, editable report, or system view that does not retain history.`,
 `Protect data while making the packet reviewable. Keep identity, payment, personnel, health, contract, or security details in the approved system and expose only the minimum fields needed in the working queue. Use masked tokens and stable references rather than copying secrets. If a case requires a recipient change or cross-customer comparison, stop and involve the privacy or security owner before sharing. Evidence completeness never justifies uncontrolled duplication of sensitive records.`,
 `Reconstruct the chronology with original timestamps and timezones. Include creation, receipt, assignment, acknowledgement, change, approval, hold, send, implementation, failure, correction, and verification. Add UTC values for comparison without replacing what systems displayed. Identify the actor or automated process and resulting state. A current status cannot prove what evidence existed earlier. Preserve unsuccessful attempts and reversals because they explain why the latest state changed and whether another owner relied on an earlier version.`,
 `Create a field comparison with source citations. Compare identifiers, parties, owner, scope, status, version, dates, permissions, approval state, and next action. Classify each row as aligned, different, missing, superseded, not applicable, or requiring owner interpretation. Do not overwrite a source value to force agreement. Formatting variations can be normalized while originals remain visible. A different entity, recipient, authority, policy version, access role, customer promise, or controlled status needs the named owner.`,
 `Test stop conditions before work continues. Stop when identity is uncertain, evidence points to different customers or entities, sensitive data would cross an unauthorized boundary, policy or contract must be interpreted, access is excessive or absent, approval is missing, or implementation could create an irreversible consequence. Record the reason, affected work, owner, evidence checked, and next review time. “Blocked” without this detail is not a useful state for a distributed support lane.`,
 `Prepare one bounded handoff. Summarize what agrees, what conflicts, what remains unavailable, and the operational consequence. Ask ${s.owner}: ${s.decision}? Link the source register, event chronology, comparison table, and minimum necessary evidence. Include a response date, but never treat urgency as approval. A second reviewer should reproduce the facts without private context, and the owner should be able to decide without repeating the entire investigation.`,
 `Use precise queue states such as source missing, identity unresolved, version conflict, approval pending, owner interpretation required, implementation pending, verification pending, or disposition recorded. If responsibility transfers, retain the old owner, new owner, transfer time, open question, attached evidence, and acknowledgement. Do not mark an item complete merely because it moved to another inbox. Ownership transfer is an event that needs its own evidence.`,
 `After an authorized decision, verify the implemented result against the right record. Capture decision owner, time, reason, approved value or state, implementing actor, and system result. Check that a correction did not affect another case, entity, version, message, or reporting period. A successful status is not proof when the wrong target can also succeed. Preserve before-and-after evidence and append later corrections rather than rewriting the history used by previous reviewers.`,
 `Close only when the original question has an attributable disposition and each residual item has an owner. Check related drafts, duplicate cases, stale messages, old permissions, reports, automations, and pending actions. Communicate externally only with approved wording and verified recipients. If the customer or employee outcome cannot yet be confirmed, state what was verified and what remains pending rather than converting an internal action into a promise of resolution.`,
 `Measure quality without rewarding unsafe speed. Useful measures include source completeness, time to named ownership, evidence-request cycles, reopen rate, classification agreement, implementation mismatches, and repeated causes. Do not rank staff by holds removed or cases closed. A controlled stop can be correct. Publish definitions, numerators, denominators, exclusions, and observation windows so leaders distinguish a real process signal from a polished but unstable metric.`,
 `Test the procedure with an ordinary case, missing evidence, conflicting identity, urgent request, owner transfer, and a case that changes after approval. Give a backup reviewer only the retained packet and ask for the source, chronology, conflict, owner question, decision, and implemented result. Repair the checklist wherever undocumented knowledge was required. A process is not repeatable merely because its original specialist remembers what happened.`,
 `Finish with an owner action register. Each recurring defect needs evidence, accountable owner, date, acceptance check, and result. System design, policy, training, access, and communication may require different owners. Support can quantify patterns and maintain the queue, but management owns control design and risk acceptance. Publish the working rule with effective date, version, approved channels, access limits, stop conditions, and examples so future reviewers know what governed each case.`
 ,`Run a short calibration before the lane becomes routine. Give the support specialist and owner the same ordinary case, ambiguous case, sensitive case, and post-approval change. Compare not only their proposed result but also the source, rule, stop condition, and evidence each person used. Apparent agreement can hide different reasoning that fails on the next item. Record disagreements, owner adjudication, and any approved example added to the procedure. If the rule changes materially, retain the old version and identify which open cases must be reconsidered rather than silently applying the new interpretation backward.`
 ,`A daily handoff should remain concise and decision-ready: population checked, records ready, exceptions by evidence state, oldest open item, decisions needed, work paused, and next verification. Counts must reconcile to the queue and link to controlled evidence. Avoid narrative that assigns blame or exposes personal information. The useful outcome is continuity: another authorized person can resume the lane, understand why work stopped, contact the right owner, and verify the eventual result without asking the original specialist to reconstruct a private conversation.`
];
export const oct8BlogPosts=blogSpecs.map(s=>({slug:s.slug,title:s.title,excerpt:s.excerpt,minutes:12,publishedAt:published,heroImage:hero}));
export const oct8BlogBasics=Object.fromEntries(blogSpecs.map(s=>{const p=common(s);return [s.slug,{intro:p[0],sections:[{title:'Define the evidence and authority boundary',paragraphs:p.slice(1,4),checks:['Are the authoritative sources and versions named?','Is the decision owner explicit?']},{title:'Reconstruct the chronology and differences',paragraphs:p.slice(4,7),checks:['Do original timestamps and values remain visible?','Are stop conditions documented?']},{title:'Route and verify the owner decision',paragraphs:p.slice(7,11),checks:['Can a second reviewer reproduce the packet?','Was implementation checked against the correct target?']},{title:'Make the Philippines support lane repeatable',paragraphs:p.slice(11),checks:['Are metrics defined with denominators?','Does the procedure include backup review and version control?']}],servicePath:'/services/operations-support',serviceLabel:'Philippines operations support',sources:[{name:'GAO Green Book',url:sources[0]},{name:'NIST SP 800-53 Rev. 5',url:sources[1]},{name:'NIST Privacy Framework',url:sources[2]}]}]}));

type ResearchSpec={slug:string;title:string;excerpt:string;question:string;population:string;signals:string[]};
const researchSpecs:ResearchSpec[]=[
 {slug:'philippines-handoff-acceptance-latency-research',title:'Philippines Support Handoff Acceptance Latency Research',excerpt:'A time-aware study of sent, received, acknowledged, and owner-ready handoffs across distributed shifts.',question:'how long handoffs wait for attributable acceptance and which evidence gaps explain the delay',population:'routine, urgent, cross-team, and returned handoffs in Philippines support lanes',signals:['send event','recipient identity','receipt evidence','acceptance event','open obligations','first owner action']},
 {slug:'philippines-customer-update-source-lineage-research',title:'Philippines Customer Update Source-Lineage Research',excerpt:'Test whether outbound updates trace to the exact source version and approval available when sent.',question:'whether a customer update can be reconstructed from the source and approval available at send time',population:'status emails, case replies, notices, and manager-approved customer updates',signals:['source version','draft version','approval event','send event','recipient scope','later correction']},
 {slug:'philippines-queue-owner-agreement-research',title:'Philippines Service Queue Owner-Agreement Research',excerpt:'A blinded review of whether independent reviewers identify the same current owner and escalation route.',question:'whether independent reviewers assign the same accountable owner and stop condition from frozen evidence',population:'cases spanning support, operations, reporting, recruiting, administration, and exception queues',signals:['case identity','current owner','policy source','unresolved decision','stop condition','escalation route']},
 {slug:'philippines-work-access-removal-evidence-research',title:'Philippines Work Access Removal Evidence Research',excerpt:'A least-privilege protocol for accounts, sessions, tokens, automations, and saved artifacts at offboarding.',question:'whether access and reusable artifacts are removed or reassigned at the authorized time',population:'departing employees, contractors, shared roles, service accounts, sessions, tokens, and automations',signals:['identity inventory','role removal','session revocation','token rotation','artifact ownership','post-removal test']},
 {slug:'philippines-reopened-exception-recurrence-research',title:'Philippines Reopened Exception Recurrence Research',excerpt:'Distinguish incomplete closure, new evidence, and recurring workflow defects in distributed service queues.',question:'why closed exceptions reopen and which patterns point to evidence, ownership, system, or workflow defects',population:'exceptions reopened after recorded closure across service, customer, access, and reporting workflows',signals:['original cause','closure basis','new trigger','same-record recurrence','owner transfer','corrective action']}
];
const makeResearch=(s:ResearchSpec):ResearchPost=>({slug:s.slug,title:s.title,excerpt:s.excerpt,published,hero,statistic:`Six evidence signals: ${s.signals.join(', ')}.`,methodology:`A bounded reproducible study of ${s.population}. Sources checked October 8, 2026. It measures evidence and workflow state, not individual performance or legal validity.`,sources,related:[],serviceHandoff:{slug:'operations-support',label:'Plan Philippines operations support',text:'Use a source-linked evidence queue while accountable owners retain policy, approval, access, and customer decisions.'},faqs:[{question:'What does this study measure?',answer:s.question+'.'},{question:'What stays with the client owner?',answer:'Policy interpretation, sensitive exceptions, approvals, access authority, customer commitments, and risk acceptance.'},{question:'Can support fill gaps by inference?',answer:'No. Missing or conflicting evidence remains visible and is routed.'}],dataSections:[{heading:'Evidence signals',text:s.signals.join(', ')},{heading:'Decision use',text:'Use results to improve sources, ownership, access, and verification—not to rank individuals by speed.'}],body:[
 `This study asks ${s.question}. It examines ${s.population}. The output is a reproducible register and owner-facing decision packet, not a declaration that a transaction or action is valid. GAO's Green Book provides a framework for responsibility, quality information, control activities, and monitoring. NIST SP 800-53 supports attributable events and restricted permissions. The NIST Privacy Framework and National Archives guidance reinforce purposeful collection and durable evidence. Company policy and accountable owners determine actual treatment.`,
 `The population includes completed, held, rejected, transferred, corrected, superseded, and reopened items. Each row retains entity, stable case ID, channel, party, source versions, intake time, queue state, assigned owner, reviewer, decision event, implementation event, and final disposition. Primary observations are ${s.signals.join(', ')}. Selection rules are frozen before measurement and every exclusion receives a reason. Sensitive identity, customer, personnel, payment, and security data remains masked in analytical files.`,
 `Time is treated as evidence. Each event retains original timestamp, timezone, actor or process, system, and stable event ID. UTC is added for comparison without replacing the original. Intake, packet-ready, routing, acknowledgement, evidence request, response, decision, implementation, and verification are separate. That distinction prevents waiting for missing sources from being attributed to an owner and prevents post-decision implementation time from being attributed to a preparer. Clock conflicts remain explicit limitations.`,
 `Source preservation precedes analysis. Original messages, documents, exports, workflow histories, approvals, role assignments, and correspondence receive stable identifiers or hashes where permitted. Extracted values remain linked to the source and version. A current screen cannot prove what an earlier reviewer saw, and a replaced file cannot retroactively become the basis for a prior decision. Historical and later records stay connected by explicit change events.`,
 `Reviewers use explicit classifications for ${s.signals.join(', ')}: aligned, different, missing, superseded, not applicable, or owner interpretation required. Calculations expose inputs, denominators, exclusions, precision, and result. Familiar names, matching totals, a successful status, or a prior case are not proof. Those observations guide review but cannot resolve identity, authority, policy version, scope, recipient, access, or customer commitments.`,
 `Quality is tested with blinded second review. Two reviewers receive the same frozen packet and independently record signals, missing evidence, current owner, stop condition, and bounded decision request. Agreement is measured separately for facts, classification, routing, and closure. Disagreements are adjudicated against sources and definitions rather than by choosing the faster answer. Original responses remain retained so later taxonomy improvements do not erase earlier ambiguity.`,
 `Challenge cases include similar names across two entities, a replaced attachment, timestamps near cutoff, approval followed by source change, an automated state without an actor, overlapping owners, transferred queues, sensitive recipient change, rejected action later retried, and closure followed by new evidence. The method passes when reviewers reconstruct the same sources, chronology, differences, and accountable decision point. It fails when current state substitutes for history or a support role resolves a controlled decision to improve a metric.`,
 `Role boundaries are integral. Philippines support may inventory sources, normalize timestamps, prepare comparisons, maintain an evidence queue, calculate declared measures, and route questions. It may not interpret policy beyond written rules, approve customer exceptions, disclose sensitive data, grant privileged access, impersonate an owner, change contract meaning, or promise an outcome. Business, privacy, security, reporting, system, and executive owners retain their assigned decisions.`,
 `Measures include population completeness, source completeness, packet-ready rate, acknowledgement time, decision time, implementation time, evidence-request cycles, classification agreement, reopened items, repeated causes, and verified closure. Report distributions and denominators, not only averages. Stratify by cause, channel, service, owner role, risk, and workflow when samples permit. Do not rank individuals by raw speed or reward closure alone; a correct controlled stop can take longer.`,
 `Limitations include overwritten histories, inaccessible external systems, shared identities, clock drift, policy ambiguity, informal decisions, missing customer events, and small samples. The study cannot prove intent, fraud, legal validity, contractual authority, customer satisfaction, or causation from correlation. Its conclusion is narrower: ${s.question} can be examined when population, sources, chronology, roles, classifications, decisions, implementation, and limitations remain visible.`,
 `The final artifact contains methods, frozen population, dictionary, source register, taxonomy, chronology, reviewer-agreement table, findings with denominators, challenge results, limitations, and action register. Each action names its owner, evidence, date, and verification method. A case summary shows ${s.signals.join(', ')} and links each to records. Corrections append a version rather than rewriting history, keeping preparation separate from approval.`,
 `Pilot one ordinary path, one missing-source path, one identity or ownership conflict, one urgent item, and one event changing after decision. Ask an independent reviewer to reconstruct the same signals, state, and owner question. Dependence on private chat, memory, or undocumented screens becomes a recorded gap. The owner decides whether to change the source system, procedure, access model, or review cadence. A pilot tests the workflow; it does not prove every future case behaves the same.`,
 `Reporting separates observations, interpretations, recommendations, and decisions. Observations cite records; interpretations state assumptions; recommendations name mechanisms; decisions identify authorized people and effective times. Negative findings identify the test performed because “no issue found” without method is not evidence. Retain extraction time, query version, and reviewer with every table so later analysts can reproduce counts and explain changes caused by corrected sources or expanded populations.`
 ,`Sampling must reflect the decision the owner intends to make. Include every high-consequence exception defined before review, then select ordinary records with a reproducible random or systematic method. Do not replace unavailable evidence with convenient cases while preserving the headline sample size. Keep selected, available, reviewed, excluded, unscorable, replaced, and unresolved counts separate. Compare original and final samples on channel, age, issue type, owner role, and risk state. If missing evidence concentrates in difficult cases, publish that limitation rather than allowing a clean reviewed subset to represent the whole population.`
 ,`Access and separation of duties are tested alongside content. Reviewers need the minimum read permissions required for the frozen evidence; preparation does not require authority to change assignments, approve exceptions, alter customer records, grant access, or release communications. Record individual identities for material actions and set expiry for temporary access. When a reviewer cannot obtain evidence safely, route the gap to the system or privacy owner. A broader permission granted merely to finish the study can introduce more risk than the workflow question justifies and can make later reproduction depend on exceptional access.`
 ,`The owner action register links every recurring finding to a proposed mechanism, accountable role, required evidence, target date, acceptance test, and post-change observation. Repeated missing timestamps may call for logging; recurring ownership ambiguity may require a routing rule; overwritten source versions may require retention; inconsistent decisions may require policy examples. Training is not the default explanation when the interface, data model, or authority map is unclear. After an approved change, test new cases and an unaffected control set. Preserve the old measurement so improvement claims compare defined methods rather than rewritten history.`
 ,`A final decision brief should state what the evidence supports and what it cannot support. It names the population and period, shows all denominators, describes unavailable records, distinguishes association from causation, and identifies unresolved high-consequence cases individually under controlled access. It does not generalize one Philippines support lane to all workers, companies, channels, or future periods. The supported management choice may be to expand, retain, narrow, pause, or repair the lane. Whichever choice is made, record its owner, rationale, effective time, affected scope, and the next verification point.`
]});
export const oct8ResearchPosts:ReadonlyArray<ResearchPost>=researchSpecs.map(makeResearch);
