export const roleGallery = [
  { src: "/illustrations/role-gallery/role-art-01.webp", label: "Achievement and Success", topic: "Achievement and Success" },
  { src: "/illustrations/role-gallery/role-art-02.webp", label: "Achievement and Success", topic: "Achievement and Success" },
  { src: "/illustrations/role-gallery/role-art-03.webp", label: "Achievement and Success", topic: "Achievement and Success" },
  { src: "/illustrations/role-gallery/role-art-04.webp", label: "Achievement and Success", topic: "Achievement and Success" },
  { src: "/illustrations/role-gallery/role-art-05.webp", label: "Avatars and Characters", topic: "Achievement and Success" },
  { src: "/illustrations/role-gallery/role-art-06.webp", label: "Business and Finance", topic: "Achievement and Success" },
  { src: "/illustrations/role-gallery/role-art-07.webp", label: "Business and Finance", topic: "Business and Finance" },
  { src: "/illustrations/role-gallery/role-art-08.webp", label: "Business and Finance", topic: "Business and Finance" },
  { src: "/illustrations/role-gallery/role-art-09.webp", label: "Business and Finance", topic: "Business and Finance" },
  { src: "/illustrations/role-gallery/role-art-10.webp", label: "Business and Finance", topic: "Business and Finance" },
  { src: "/illustrations/role-gallery/role-art-11.webp", label: "Business and Finance", topic: "Business and Finance" },
  { src: "/illustrations/role-gallery/role-art-12.webp", label: "Business and Finance", topic: "Business and Finance" },
  { src: "/illustrations/role-gallery/role-art-13.webp", label: "Business and Finance", topic: "Data and Analytics" },
  { src: "/illustrations/role-gallery/role-art-14.webp", label: "Business and Finance", topic: "Idea generation" },
  { src: "/illustrations/role-gallery/role-art-15.webp", label: "Creative Design", topic: "Achievement and Success" },
  { src: "/illustrations/role-gallery/role-art-16.webp", label: "Creative Design", topic: "Creative Design" },
  { src: "/illustrations/role-gallery/role-art-17.webp", label: "Education and Training", topic: "Education and Training" },
  { src: "/illustrations/role-gallery/role-art-18.webp", label: "Education and Training", topic: "Education and training" },
  { src: "/illustrations/role-gallery/role-art-19.webp", label: "Education and Training", topic: "Reading" },
  { src: "/illustrations/role-gallery/role-art-20.webp", label: "Food and Cuisine", topic: "Food and Cuisine" },
  { src: "/illustrations/role-gallery/role-art-21.webp", label: "Health and Wellness", topic: "Hand gesture" },
  { src: "/illustrations/role-gallery/role-art-22.webp", label: "Health and Wellness", topic: "Health and Wellness" },
  { src: "/illustrations/role-gallery/role-art-23.webp", label: "Health and Wellness", topic: "Lifestyle and Leisure" },
  { src: "/illustrations/role-gallery/role-art-24.webp", label: "Legal and Justice", topic: "Law and Justice" },
  { src: "/illustrations/role-gallery/role-art-25.webp", label: "Lifestyle and Leisure", topic: "Lifestyle and Leisure" },
  { src: "/illustrations/role-gallery/role-art-26.webp", label: "Lifestyle and Leisure", topic: "Lifestyle and Leisure" },
  { src: "/illustrations/role-gallery/role-art-27.webp", label: "Lifestyle and Leisure", topic: "Rainy day" },
  { src: "/illustrations/role-gallery/role-art-28.webp", label: "Lifestyle and Leisure", topic: "Relaxation" },
  { src: "/illustrations/role-gallery/role-art-29.webp", label: "Marketing and Advertising", topic: "Customer feedback" },
  { src: "/illustrations/role-gallery/role-art-30.webp", label: "Music and Entertainment", topic: "Music and Entertainment" },
  { src: "/illustrations/role-gallery/role-art-31.webp", label: "Music and Entertainment", topic: "Music and Entertainment" },
  { src: "/illustrations/role-gallery/role-art-32.webp", label: "Music and Entertainment", topic: "Music and Entertainment" },
  { src: "/illustrations/role-gallery/role-art-33.webp", label: "Music and Entertainment", topic: "Music and Entertainment" },
  { src: "/illustrations/role-gallery/role-art-34.webp", label: "Photography", topic: "Photography" },
  { src: "/illustrations/role-gallery/role-art-35.webp", label: "Relationships", topic: "Relationships" },
  { src: "/illustrations/role-gallery/role-art-36.webp", label: "Science and Research", topic: "Science and Research" },
  { src: "/illustrations/role-gallery/role-art-37.webp", label: "Scribble", topic: "Question mark" },
  { src: "/illustrations/role-gallery/role-art-38.webp", label: "Social Media and Communication", topic: "Selfie" },
  { src: "/illustrations/role-gallery/role-art-39.webp", label: "Social Media and Communication", topic: "Social Media and Communication" },
  { src: "/illustrations/role-gallery/role-art-40.webp", label: "Task Management", topic: "Problem solving" },
  { src: "/illustrations/role-gallery/role-art-41.webp", label: "Tech and Innovation", topic: "Cartoon character" },
  { src: "/illustrations/role-gallery/role-art-42.webp", label: "Tech and Innovation", topic: "Tech and Innovation" },
  { src: "/illustrations/role-gallery/role-art-43.webp", label: "Tech and Innovation", topic: "Technology" },
  { src: "/illustrations/role-gallery/role-art-44.webp", label: "Travel and Adventure", topic: "Travel and Adventure" },
  { src: "/illustrations/role-gallery/role-art-45.webp", label: "Travel and Adventure", topic: "Travel and Adventure" },
  { src: "/illustrations/role-gallery/role-art-46.webp", label: "Work and Employment", topic: "Work and Employment" },
] as const;
