type ResearchPost={slug:string;title:string;excerpt:string;published:string;statistic:string;methodology:string;body:readonly string[];dataSections:readonly {heading:string;text:string}[];faqs:readonly {question:string;answer:string}[];sources:readonly string[];related:readonly string[];hero:string;serviceHandoff:{slug:string;label:string;text:string}};
const published='2026-09-01';
export const sep1ResearchPosts:readonly ResearchPost[]=[
 {slug:'philippines-editorial-claim-traceability-research',title:'Philippines Editorial Operations: Can Claim Traceability Reduce Review Rework?',excerpt:'A research framework for testing whether sentence-level evidence states make daily article review faster without weakening editorial judgment.',published,statistic:'The Philippine Statistics Authority publishes statistical releases with reference periods and technical notes, illustrating why a claim needs more than a nearby source URL to remain interpretable.',methodology:'This qualitative desk review compares publication practices described by the Philippine Statistics Authority, OECD, and US Government Publishing Office. It uses those primary materials to define a shadow review of claim provenance. No client drafts or unpublished records were examined. The proposed fields and measures are operating hypotheses, not findings about worker performance.',body:[
  'Research question: can a Philippines-based editorial assistant reduce avoidable review work by recording the provenance and status of material claims before an editor reads the full draft? Daily publishing often joins observations, interpretations, and company assertions in one paragraph. A citation may be accurate yet fail to support the conclusion placed beside it. The testable unit is therefore one material claim with its evidence state, not the number of links collected.',
  'Primary publishers provide a useful model because they expose dates, definitions, and revision context. PSA releases identify reference periods and methods. OECD datasets carry metadata that helps a reader interpret an indicator. The US Government Publishing Office documents authentication and version context for official publications. These practices do not dictate a private editorial workflow, but they show why provenance, scope, and time belong beside a claim.',
  'A claim record can include draft location, claim text, classification, source URL, source owner, observation period, retrieval date, supporting passage, limitation, and reviewer disposition. Classifications should distinguish direct observation, calculation, synthesis, company-supplied fact, and editorial recommendation. When a source conflicts with the sentence, the assistant flags the mismatch rather than editing toward a plausible statement without approval.',
  'Test the method on a dated sample containing straightforward facts, qualified statistics, cross-source synthesis, and claims intentionally lacking support. Compare ordinary review with the claim-record review. Measure unsupported-claim discovery, correction reason, reviewer lookup time, false confidence created by irrelevant citations, and final disposition. A faster review is not better if unsupported conclusions survive.',
  'The authority boundary remains important. Research support can locate material, quote a limited passage, record dates, and identify gaps. The editor decides relevance, wording, interpretation, commercial emphasis, and publication. Legal, medical, financial, or client-specific assertions require the appropriate accountable reviewer. Public sources cannot approve the use made of them in a particular article.',
  'Evidence-led conclusion: traceability is useful when it makes the reviewer’s decision easier to reproduce. It becomes overhead when every ordinary sentence receives an elaborate record or when a status label substitutes for reading the source. A narrow, risk-based register and a clear escalation state offer the strongest basis for a controlled pilot.'
 ],dataSections:[{heading:'Proposed comparison',text:'Compare claim-level defects and reviewer effort across matched drafts reviewed with and without the provenance record; retain counts, denominators, and correction reasons.'},{heading:'Decision boundary',text:'Support records evidence and uncertainty. The accountable editor approves interpretations, public wording, and publication.'}],faqs:[{question:'Does a source link make a claim verified?',answer:'No. A reviewer must still check whether the source supports the exact claim, period, population, and scope.'},{question:'Which claims need the fullest record?',answer:'Prioritize statistics, consequential factual assertions, company claims, comparisons, and conclusions built from multiple sources.'}],sources:['https://psa.gov.ph/statistics','https://www.oecd.org/en/data.html','https://www.gpo.gov/how-to-work-with-us/agency/services-for-agencies/authentication'],related:['philippines-content-source-review-research','philippines-source-quality-evidence-research'],hero:'/aug31-research-heroes/ecommerce-chargeback-evidence.png',serviceHandoff:{slug:'reporting-and-quality-assurance',label:'Plan reporting and QA support',text:'Turn the claim-state model into a sampled review lane with an editor-owned approval step.'}},
 {slug:'philippines-content-review-queue-aging-research',title:'Philippines Content Review: What Does Queue Aging Reveal About Daily Publishing?',excerpt:'A bounded study design for separating writing speed from reviewer capacity, blocked decisions, and evidence-related delay.',published,statistic:'Little’s Law relates average work in process, throughput, and flow time in a stable system; applying it to an editorial queue requires consistent units and a clearly defined observation window.',methodology:'This desk review uses primary operations-management material from MIT OpenCourseWare and public service-management guidance from the UK Government Digital Service. It translates queue concepts into an editorial shadow study. The thresholds and workflow are proposals to validate locally, not industry benchmarks.',body:[
  'Research question: what can the age of a content-review queue reveal that a daily draft count cannot? An article may wait because its editor is unavailable, its evidence is incomplete, its route conflicts with another release, or a consequential claim needs a named owner. Combining those states into “waiting for review” conceals the control that must change.',
  'Queue theory provides relationships, not a ready-made staffing target. Little’s Law can connect work in process, throughput, and flow time under stated assumptions. Government service guidance emphasizes understanding user needs and measuring performance in context. Editorial work varies in risk and review type, so an average should not be treated as a promise for every article.',
  'Build an event record for each draft: ready time, requested review type, reviewer, first-touch time, return reason, correction-ready time, approval time, publication time, and hold intervals. Pause the editorial-aging clock when the item is explicitly waiting for an external decision, but report that held time separately. Never erase it from the history.',
  'Use a four-week shadow sample before changing targets. Segment factual review, structural edit, commercial approval, specialist review, and technical release check. Report median and percentile age with sample counts, work in process, arrival volume, and completed volume. Review individual long-wait cases because a small queue produces unstable summary measures.',
  'The coordinator can maintain timestamps, classify an item under approved definitions, and surface breaches. The editor or publishing owner decides priority, acceptable carryover, review depth, and release. A worker should not publish an aged item merely to improve the dashboard or quietly downgrade its required review.',
  'Evidence-led conclusion: queue aging is most valuable as a diagnostic for ownership and capacity. It cannot show article quality by itself. Paired with return reasons and review classes, it helps OutsourcedPhilippines.com set daily routines around real decision capacity instead of rewarding draft accumulation.'
 ],dataSections:[{heading:'Minimum measures',text:'Track arrivals, completions, work in process, active review age, held age, return reason, and review class with a fixed observation period.'},{heading:'Interpretation limit',text:'Age identifies where to inspect. It does not prove whether a draft is accurate, useful, or ready to publish.'}],faqs:[{question:'Should held time be excluded?',answer:'Keep it visible as a separate measure so external dependencies do not distort active-review time or disappear from accountability.'},{question:'Is one average enough?',answer:'No. Include the denominator, distribution, review class, and representative long-wait cases.'}],sources:['https://ocw.mit.edu/courses/15-760a-operations-management-spring-2002/','https://www.gov.uk/service-manual/measuring-success'],related:['philippines-work-queue-design-research','philippines-review-consistency-research'],hero:'/aug31-research-heroes/bookkeeping-close-cutoff.png',serviceHandoff:{slug:'content-moderation',label:'Plan content operations support',text:'Define event states and review ownership before measuring a live editorial queue.'}},
 {slug:'philippines-article-canonical-integrity-research',title:'Philippines Publishing QA: How Should Canonical Integrity Be Tested?',excerpt:'A route-level research protocol for checking that each new article has one reachable identity across metadata, indexes, and sitemaps.',published,statistic:'Google Search Central describes canonicalization as selecting a representative URL among duplicate or very similar pages, while sitemap inclusion is a separate discovery signal rather than proof of canonical correctness.',methodology:'This technical desk review uses primary Google Search Central and RFC materials to distinguish response identity, canonical hints, redirects, and sitemap discovery. The proposed route matrix is a local QA protocol. It does not predict ranking or indexing outcomes.',body:[
  'Research question: what evidence establishes that a newly published article has its own canonical identity? A title in a source file is insufficient. The intended route must resolve, render the intended body, identify itself in canonical metadata, appear in the correct archive, and occur in the sitemap without borrowing another page’s output.',
  'HTTP status, final URL, HTML canonical, structured-data URL, and discovery links answer different questions. RFC semantics explain the response layer. Google documents canonical signals and sitemap practices for search systems. A 200 response can still be a soft fallback, while a sitemap entry can point to a page whose canonical names another route.',
  'Create one matrix row per manifest item with family, slug, expected absolute URL, response status, redirect chain, canonical value, title, visible date, datePublished, content hash, index occurrence, and sitemap occurrence. Fetch unknown control routes as well as intended routes to detect generic fallbacks. Hash normalized article bodies, not whole pages whose shared layout will dominate.',
  'Test exact counts before inspecting presentation. Duplicate slugs, URLs, canonicals, or body hashes stop the batch. Then request every route and compare its returned identity with the row. Verify that each Blog item is linked from Blog pagination and each Research item from Research. The sitemap must contain each canonical URL once after set normalization.',
  'Technical support can execute checks and report mismatches. The release owner decides whether to correct, hold, or roll back. A passing local build does not authorize deployment, and a canonical tag should never be changed merely to make a test agree with an unintended route.',
  'Evidence-led conclusion: canonical integrity is a chain of consistent observations, not one metadata field. A compact manifest-driven checker can prove internal release coherence. Search-engine crawling and indexing remain external processes and should not be claimed as outcomes of local validation.'
 ],dataSections:[{heading:'Identity chain',text:'Compare manifest, response, visible page, canonical metadata, JSON-LD, landing-page link, and sitemap URL for the same absolute route.'},{heading:'What the test cannot prove',text:'Local route integrity cannot guarantee crawl timing, search indexing, ranking, or the absence of external links to obsolete URLs.'}],faqs:[{question:'Is HTTP 200 enough?',answer:'No. The response must also render the intended distinct article and identify its own canonical URL.'},{question:'Why hash article bodies?',answer:'Distinct normalized body hashes help detect duplicate route rendering that different titles or shared layouts could hide.'}],sources:['https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls','https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview','https://www.rfc-editor.org/rfc/rfc9110'],related:['philippines-outsourced-article-schema-review','philippines-website-content-audit-research'],hero:'/aug31-research-heroes/property-deadline-control.png',serviceHandoff:{slug:'reporting-and-quality-assurance',label:'Plan publishing QA support',text:'Use a manifest-driven route matrix with release ownership and exception handling.'}},
 {slug:'philippines-daily-content-brief-completeness-research',title:'Philippines Content Operations: Can Brief Completeness Predict Draft Rework?',excerpt:'A cautious study design for testing which intake fields reduce avoidable editorial returns without turning a brief into a writing substitute.',published,statistic:'The UK Government Digital Service recommends beginning with user needs and writing in a way users can understand; those principles do not prescribe a universal content-brief length.',methodology:'This review draws on primary content-design guidance from GOV.UK and plain-language guidance from the US government. It proposes a matched retrospective coding study of brief fields and return reasons. No OutsourcedPhilippines.com production data were analyzed, so no causal performance claim is made.',body:[
  'Research question: are some missing brief fields consistently associated with avoidable draft returns? A longer brief is not automatically better. The useful test is whether a specific input helps a writer make a decision the editor would otherwise reverse, such as audience, reader question, evidence boundary, excluded promise, route family, or required next step.',
  'Public content guidance emphasizes user need, clarity, and accessible language. Those principles help define what a brief should enable, but they do not establish which template works for a particular company. The site must test its fields against its own article types, decision owners, and sources.',
  'Code a historical sample using only information that existed when work began. Record whether each proposed field was explicit, implicit, conflicting, or absent. Separately code the first editorial return reason: direction, evidence, structure, voice, scope, duplication, commercial approval, or technical identity. Reviewers should not infer a good brief from a good final article.',
  'Compare return patterns within similar article families and risk classes. Report counts and denominators, not only rates. A field may correlate with fewer returns because experienced editors use it on easier work. Follow the quantitative comparison with case review and a prospective pilot before changing the mandatory template.',
  'An editorial assistant can prepare source lists, surface missing fields, and record the owner’s answer. The commissioning editor owns audience, public position, exclusions, and acceptance. When the reader question or commercial promise is unresolved, the safe state is held rather than filled with a reasonable-sounding assumption.',
  'Evidence-led conclusion: brief completeness should be treated as a local design question. A small set of decision-bearing fields may reduce rework, while extra prose can make important constraints harder to find. The right output is a tested minimum brief with explicit exception handling.'
 ],dataSections:[{heading:'Candidate intake fields',text:'Test reader, question, outcome, route, evidence, exclusions, owner, review type, and due window separately rather than scoring only total completeness.'},{heading:'Causal caution',text:'Association between a field and fewer returns may reflect article difficulty, editor experience, or selection effects.'}],faqs:[{question:'Should every brief use the same template?',answer:'Use a shared minimum, then add fields required by the article family or risk; test changes against actual return reasons.'},{question:'What happens when a key field is missing?',answer:'Route one narrow question to the responsible editor and keep the item held until the decision is recorded.'}],sources:['https://www.gov.uk/guidance/content-design/writing-for-gov-uk','https://www.plainlanguage.gov/guidelines/'],related:['philippines-article-brief-research','philippines-knowledge-transfer-research'],hero:'/aug31-research-heroes/legal-intake-conflict-routing.png',serviceHandoff:{slug:'content-moderation',label:'Plan editorial coordination support',text:'Pilot a minimum brief with coded return reasons and an editor-owned acceptance gate.'}},
 {slug:'philippines-publication-date-consistency-research',title:'Philippines Article Publishing: Why Must Visible and Structured Dates Agree?',excerpt:'A research-led QA method for keeping publication identity consistent across reader-facing text, JSON-LD, metadata, and release records.',published,statistic:'Schema.org defines datePublished as the date of first publication, while Google’s article documentation recommends clear, visible dates and consistent structured data.',methodology:'This desk review compares primary Schema.org and Google Search Central documentation with HTTP date semantics from RFC 9110. It proposes a date-consistency test for static article releases. The protocol assesses internal agreement, not search display eligibility or indexing.',body:[
  'Research question: how should a publisher verify the date identity of a daily article batch? Dates can appear in visible text, time elements, Article JSON-LD, metadata, sitemap extensions, source manifests, and deployment records. If those values disagree, readers and machines receive different accounts of when the work was published.',
  'Schema.org provides the datePublished property, and Google’s article guidance discusses visible and structured dates. HTTP response dates describe message origination and are not substitutes for article publication dates. These sources support consistency checks but do not decide an organization’s editorial policy for corrections, updates, or substantial republication.',
  'The route-level record should include intended first-publication date, visible label, time-element value, datePublished, dateModified, source value, canonical URL, build identifier, and check time. Parse structured data rather than searching raw HTML for a date string. Confirm that the visible reader date represents the same calendar day and time-zone policy.',
  'Test all new routes plus control pages from the prior release. The new batch must match its intended day while earlier pages remain unchanged. Compare values by canonical route and flag missing, malformed, future, or conflicting dates. A shared date in navigation or footer must not be mistaken for the article’s own date.',
  'Editorial ownership matters when content changes. Technical support may report inconsistencies and implement an approved correction, but the publisher decides whether a change affects dateModified, warrants a correction notice, or constitutes a new publication. Tests should enforce recorded policy rather than invent it.',
  'Evidence-led conclusion: date consistency is a small but consequential release control. It proves that the site presents one internal publication record for each route. It does not prove external indexing, freshness treatment, or entitlement to a particular search presentation.'
 ],dataSections:[{heading:'Fields to reconcile',text:'Compare the source manifest, visible reader label, time datetime, Article datePublished, dateModified policy, canonical URL, and preserved prior-release controls.'},{heading:'Release safeguard',text:'Validate both the new date and unchanged earlier routes so a batch-level constant cannot rewrite publication history.'}],faqs:[{question:'Is the HTTP Date header the publication date?',answer:'No. It describes the HTTP message date, not the editorial first-publication date of the article.'},{question:'Should dateModified always equal datePublished?',answer:'That depends on the recorded editorial policy and whether the article has changed; the initial release may use the same value for both.'}],sources:['https://schema.org/datePublished','https://developers.google.com/search/docs/appearance/structured-data/article','https://www.rfc-editor.org/rfc/rfc9110'],related:['philippines-outsourced-article-schema-review','philippines-content-source-review-research'],hero:'/aug31-research-heroes/healthcare-minimum-necessary-view.png',serviceHandoff:{slug:'reporting-and-quality-assurance',label:'Plan release verification support',text:'Create a date matrix that protects new releases and unchanged publication history.'}}
];
