type ArticleInput={slug:string;title:string;excerpt:string;statistic:string;question:string;unit:string;scope:string;sourceBasis:string;population:string;procedure:string;measures:string;boundary:string;example:string;limits:string;sources:readonly string[];sourceRecord:string;related:readonly string[];serviceHandoff:{slug:string;label:string;text:string}};
type ResearchPost={slug:string;title:string;excerpt:string;published:string;statistic:string;methodology:string;body:readonly string[];dataSections:readonly {heading:string;text:string}[];faqs:readonly {question:string;answer:string}[];sources:readonly string[];related:readonly string[];hero:string;serviceHandoff:{slug:string;label:string;text:string}};
const published='2026-09-22';
const hero='/research-batch-thumbnail.jpg';

function buildArticle(a:ArticleInput):ResearchPost{return {...a,published,hero,
 methodology:`This desk review checked the named primary and authoritative sources on September 22, 2026. It translates them into a prospective eight-week review of ${a.scope}. No client account, candidate record, invoice, complaint, order, workbook, employee record, or production system was accessed. The design tests record quality and decision support, not the performance of a named worker, vendor, platform, or company.`,
 body:[
 `Research question. ${a.question} The unit of analysis is ${a.unit}. The client owner must define the eligible population, observation window, systems, required fields, and materiality threshold before extraction. Ordinary cases, corrected cases, exceptions, and records that cannot be reviewed should remain visible as separate states. The study concerns one bounded Philippines-based support lane. It does not ask whether outsourcing works in general, and it must not turn national origin into an explanation for an operational result. The useful result is whether another authorized reviewer can reproduce a finding from the same dated evidence and rule.`,
 `Evidence and interpretation. ${a.sourceBasis} These source statements are facts about the issuing bodies' own guidance or rules. They do not prove that a private organization follows the same framework, and they do not settle a client-specific legal, accounting, employment, or commercial decision. The operational inference is narrower: a support process is more reviewable when input, rule, exception, approval, and final state remain connected. Management should confirm that the cited framework fits its sector and obligations before adopting any proposed field or threshold.`,
 `Population and sampling. ${a.population} Freeze the population at a recorded cutoff and assign stable identifiers before sampling. Review every item in a client-defined high-consequence class, then draw a reproducible sample from the remaining strata. Do not replace inaccessible records with convenient ones without reporting the substitution. Record eligible, sampled, excluded, unavailable, passed, flagged, corrected, and unresolved counts. A percentage without its numerator, denominator, period, and exclusion rule is not decision-grade evidence. Small strata may need counts rather than rates, and rare but consequential exceptions may require a census.`,
 `Review procedure. ${a.procedure} The reviewer should work from a versioned checklist and preserve the exact source observed, observation time, applicable rule, result, and reason. A second reviewer should independently test a planned subset without seeing the first classification. Disagreements should be recorded and adjudicated by the named owner rather than silently overwritten. Run the procedure in shadow mode before allowing it to alter a live queue. If the source changes during review, preserve both versions and state which version controlled the decision.`,
 `Measures. ${a.measures} Report first-pass and final states separately. A flag is not an error until the authorized owner determines what the evidence means, and a correction is not verified until the intended downstream state is observed. Show reviewer agreement, missing-evidence frequency, exception age, reversal count, and time from flag to owner disposition where relevant. Speed is secondary because fast processing can hide unresolved conflicts. Segment findings only where the strata were defined in advance and large enough to interpret without exposing personal or commercially sensitive information.`,
 `Authority boundary. ${a.boundary} Philippines-based support may collect permitted evidence, apply an approved deterministic check, prepare an exception packet, and record an authorized decision. It must not invent missing facts, change a decision threshold, approve its own exception, or communicate a material commitment unless the client has explicitly assigned that authority. Use individual accounts and least-privilege access. The owner remains accountable for policy, legal interpretation, money movement, hiring selection, customer remedy, publication, and risk acceptance as applicable to the lane.`,
 `Data handling and quality control. Minimize the record to fields needed for the stated review. Candidate answers, bank details, customer messages, addresses, and other sensitive material should not be copied into general work trackers merely to prove that a check occurred. Prefer controlled identifiers, counts, reason codes, and links to authorized source systems. Define retention, correction, access removal, and incident paths before the study starts. The review log should reveal who performed the check and when, while keeping private source content in its approved system.`,
 `Analysis. Compare predefined strata and investigate clusters as workflow questions rather than individual blame. A higher flag rate may reflect harder cases, fresher detection, a changed source, a stricter reviewer, or a real control weakness. The study can establish an association within the observed lane and period. It cannot establish causation, predict future volume, or justify a broad claim about Philippines-based workers. Preserve uncertainty when evidence supports more than one explanation, and show how conclusions change when unresolved items are included or excluded.`,
 `Worked interpretation. ${a.example} The study should distinguish the observed fact, the analyst's explanation, the owner's decision, and the later verification. That separation prevents a plausible hypothesis from becoming an unsupported public claim. It also makes rework useful: if the same exception returns, the team can see whether the underlying rule, source, access, or training changed. A single worked case illustrates the method but cannot estimate prevalence. Only the frozen population and stated sample can support a rate for the observation period.`,
 `Decision use. Before the run, management should define what result would keep, revise, pause, or expand the lane. A useful threshold can combine evidence completeness, reviewer agreement, unresolved high-consequence exceptions, and correction verification rather than relying on volume alone. If the threshold is missed, inspect source quality, instructions, access, system behavior, and feedback timing before changing staffing. Expand only after ordinary items and meaningful exceptions are both reviewable. Do not let a clean pilot authorize unrelated tasks or broader access.`,
 `Limitations. ${a.limits} The protocol observes administrative evidence at recorded times, not the underlying world in full. Source guidance may be revised, client systems may transform fields, and later events can change a previously correct state. A bounded sample cannot prove that every item is accurate, compliant, fair, or commercially appropriate. The report should name unavailable evidence and deviations from the plan. Those are findings about the study's reach, not inconveniences to remove from the denominator.`,
 `Conclusion. The defensible result is modest: the organization can learn whether ${a.scope} is traceable under a named rule, source set, owner, and cutoff. That evidence can support a decision about the work lane and its controls. It cannot guarantee an outcome or transfer accountable judgment to support staff. A repeatable record of source, check, exception, decision, and verified final state is the useful product. If those elements cannot be maintained without excessive access or delay, management should narrow or stop the lane rather than compensate with assumptions.`
 ],
 dataSections:[{heading:'Source record',text:a.sourceRecord},{heading:'Minimum study record',text:`Capture the population cutoff, stable item identifier, source version, applicable rule, first review, second-review result, disagreement, owner disposition, corrected state, verification time, exclusions, and study deviation.`}],
 faqs:[{question:'Does a clean sample prove that every record is correct?',answer:'No. It supports a conclusion only about the defined population, sample, fields, rules, and observation period.'},{question:'Can support staff make the underlying decision?',answer:'Only when the client has explicitly assigned that authority. Otherwise they prepare evidence and route the decision to the named owner.'}]
 } as ResearchPost}

export const sep22ResearchPosts:readonly ResearchPost[]=[
buildArticle({
 slug:'philippines-structured-interview-scoring-consistency-research',title:'Can structured interview records make recruiting review more consistent?',excerpt:'A recruiting-coordination protocol for question control, independent scoring, disagreement review, and hiring-manager authority.',
 statistic:'The U.S. Office of Personnel Management says structured interviews ask every candidate the same predetermined questions in the same order and evaluate responses with the same rating scale and standards.',
 question:'Can a recruiting coordinator maintain consistent interview evidence without selecting candidates or interpreting employment law?',unit:'one candidate-question-rating event tied to an approved vacancy and interview-guide version',scope:'one approved structured-interview workflow',
 sourceBasis:'OPM describes structured interviewing as a systematic assessment of job-related competencies and its guide covers development, administration, and evaluation. Its public guidance identifies common questions, order, and rating standards as parts of structure.',
 population:'Include interviews completed for one role family during the window. Stratify by interview-guide version, panel, stage, delivery mode, rescheduled status, and whether a rating was revised. Keep withdrawals and incomplete interviews outside score comparisons but inside flow counts.',
 procedure:'Compare the approved guide with the invitation, questions delivered, panel membership, individual ratings, written evidence references, and final panel record. Check that panelists recorded ratings independently before discussion when the client rule requires it. Route missing ratings, altered questions, conflicts, and late changes to the hiring owner.',
 measures:'Measure guide-version match, complete independent ratings, candidate records with the approved question set, unexplained rating changes, panel disagreements, owner adjudications, and verified record completion.',
 boundary:'Coordinators may schedule, distribute the approved guide, check completeness, and prepare discrepancies. Hiring managers retain job analysis, competency choice, rating anchors, accommodation decisions, candidate evaluation, selection, rejection, and offer authority.',
 example:'Suppose two panelists use the current guide while a third scores from an older scale. The facts are the guide versions and recorded ratings. The coordinator flags the version conflict and preserves both records. The hiring owner decides whether the affected questions must be rescored, repeated, or excluded, then the reviewer verifies the authorized final record.',
 limits:'Panel training, note quality, accommodations, technology failures, candidate experience, job analysis quality, and unrecorded discussion can affect results. Record consistency does not establish validity, fairness, nondiscrimination, or the best candidate.',
 sources:['https://www.opm.gov/policy-data-oversight/assessment-and-selection/structured-interviews/','https://www.opm.gov/policy-data-oversight/assessment-and-selection/structured-interviews/guide.pdf'],sourceRecord:'Structured Interviews, U.S. Office of Personnel Management, https://www.opm.gov/policy-data-oversight/assessment-and-selection/structured-interviews/, checked September 22, 2026. Structured Interview Guide, U.S. Office of Personnel Management, https://www.opm.gov/policy-data-oversight/assessment-and-selection/structured-interviews/guide.pdf, checked September 22, 2026.',related:['philippines-recruitment-sourcing-research','philippines-recruiting-interview-scheduling-research'],serviceHandoff:{slug:'recruiting-coordination',label:'Plan recruiting coordination support',text:'Start with one role, one approved guide, and a hiring owner for every scoring exception.'}
}),
buildArticle({
 slug:'philippines-accounts-payable-duplicate-candidate-review-research',title:'How should accounts-payable teams review possible duplicate invoices?',excerpt:'A controlled review design for duplicate candidates, source evidence, approval separation, and payment-state verification.',
 statistic:'GAO guidance identifies edit checks, numerical sequence accounting, file-to-control-account comparisons, and access controls as examples of information-processing controls. GAO also states that internal control supports reliable reporting and effective operations.',
 question:'Can bookkeeping support identify plausible duplicate invoice candidates before payment without deciding whether an obligation is valid?',unit:'one invoice-payment candidate pair at a frozen accounts-payable cutoff',scope:'one approved duplicate-invoice review lane',sourceBasis:'GAO\'s 2025 Green Book organizes internal control around operations, reporting, and compliance objectives and includes preventive and detective control examples. Earlier GAO fiscal guidance explicitly discusses electronic coding and automated controls to prevent or detect duplicate payments.',
 population:'Include invoices newly entered or materially changed during the window. Stratify by supplier, currency, invoice-number normalization, amount, purchase-order presence, credit status, recurring charge, and payment state. Include reversed and voided items so the test does not treat them as invisible.',
 procedure:'Run approved exact and near-match rules over supplier identity, invoice number, amount, currency, date, purchase order, and payment reference. Compare each candidate with permitted source documents and system history. Do not delete, merge, release, hold, or recode an invoice until the accounts-payable owner decides.',
 measures:'Report candidate pairs, owner-confirmed duplicates, legitimate repeats, credits, missing evidence, review reversals, prevented releases, unresolved high-value candidates, and final payment-state verification.',
 boundary:'Support may normalize fields, run rules, assemble source links, and record dispositions. Finance owners retain supplier identity resolution, liability recognition, tax treatment, payment approval, recovery action, materiality, and accounting decisions.',
 example:'Suppose two invoices share supplier, amount, and number after punctuation is removed, but one is a credit rebill tied to a different purchase-order line. The match is an observed candidate, not a confirmed duplicate. Support assembles both records; the finance owner classifies them and approves the final state; a reviewer then verifies that neither an earned payment nor a valid credit was suppressed.',
 limits:'Supplier naming changes, split invoices, recurring amounts, credits, foreign exchange, migrated records, delayed posting, and missing purchase-order data can create false matches or hide true duplicates. The study is not an audit opinion and does not prove the legitimacy of an underlying purchase.',sources:['https://www.gao.gov/greenbook','https://www.gao.gov/assets/a76199.html'],sourceRecord:'The Green Book, U.S. Government Accountability Office, https://www.gao.gov/greenbook, checked September 22, 2026. Policy and Procedures Manual for Guidance of Federal Agencies, Title 7 Fiscal Guidance, U.S. Government Accountability Office, https://www.gao.gov/assets/a76199.html, checked September 22, 2026.',related:['philippines-accounts-payable-research','philippines-outsourcing-invoice-reconciliation-research'],serviceHandoff:{slug:'bookkeeping-support',label:'Plan bookkeeping support',text:'Start with a shadow duplicate check and keep release, recovery, and accounting decisions with finance.'}
}),
buildArticle({
 slug:'philippines-recurring-report-spreadsheet-formula-assurance-research',title:'Can formula assurance make recurring spreadsheet reports more reliable?',excerpt:'A reporting-and-QA protocol for source refresh, formula change, independent recomputation, and owner-approved release.',
 statistic:'NIST-hosted spreadsheet testing guidance recommends reviewing spreadsheet formulas against the design and warns that references to changed external workbooks can become invalid or stale.',
 question:'Can reporting support detect formula and source-reference changes before a recurring report is released?',unit:'one material report output tied to an input version, workbook version, formula path, and reporting cutoff',scope:'one recurring spreadsheet report',sourceBasis:'The NIST-hosted Best Practice Guide No. 7 discusses spreadsheet specification, testing, formula review, and risks in references to other workbooks. GAO\'s Green Book treats reliable reporting and information-processing controls as management concerns.',
 population:'Include every material output used in the approved report plus a reproducible sample of supporting calculations. Stratify by copied formula, manually entered value, lookup, external link, pivot output, hidden range, override, and changed-versus-unchanged formula.',
 procedure:'Freeze inputs and workbook versions, map each sampled output to its source and formula, refresh external connections under the approved rule, and independently recompute selected outputs outside the production cell. Compare labels, units, periods, signs, filters, and rounding as well as numeric equality. Hold discrepancies for the report owner.',
 measures:'Measure traceable outputs, formula changes with approval, stale links, hard-coded overrides, recomputation differences, label or period mismatches, owner-accepted corrections, and released outputs verified against the approved workbook.',
 boundary:'Support may refresh approved inputs, inspect formulas, recompute checks, and prepare a variance note. Report owners retain metric definitions, materiality, estimate methods, narrative interpretation, forecast decisions, and external release.',
 example:'Suppose a monthly total agrees with the prior report but its external link still points to last month\'s workbook. The fact is the stale reference, even if the displayed number looks plausible. Support records the reference and controlled recomputation. The report owner confirms the correct source and authorizes the repair before the reviewer verifies both the cell and the released report.',
 limits:'Hidden logic, macros, volatile functions, manual refresh settings, permissions, locale, rounding, external-system changes, and undocumented overrides can escape a cell-level review. Equal recomputation does not prove that the metric definition or business interpretation is appropriate.',sources:['https://www.nist.gov/document/npl-best-practice-guide-no-7-testing-spreadsheet-applications-dec2006pdf','https://www.gao.gov/greenbook'],sourceRecord:'Testing Spreadsheet Applications, Best Practice Guide No. 7, National Physical Laboratory publication hosted by NIST, https://www.nist.gov/document/npl-best-practice-guide-no-7-testing-spreadsheet-applications-dec2006pdf, checked September 22, 2026. The Green Book, U.S. Government Accountability Office, https://www.gao.gov/greenbook, checked September 22, 2026.',related:['philippines-reporting-cadence-research','philippines-client-reporting-support'],serviceHandoff:{slug:'reporting-and-quality-assurance',label:'Plan reporting and QA support',text:'Choose one recurring report and verify source, formula, owner approval, and released state.'}
}),
buildArticle({
 slug:'philippines-ecommerce-cancellation-refund-state-research',title:'How should ecommerce teams reconcile cancellation and refund states?',excerpt:'An ecommerce-operations study for request timing, shipment evidence, remedy ownership, and customer-visible status.',
 statistic:'The U.S. Federal Trade Commission Merchandise Rule requires sellers within its scope to have a reasonable basis for stated shipment times and describes cancellation and refund duties when shipment is delayed and the buyer does not consent.',
 question:'Can ecommerce operations support keep cancellation and refund evidence aligned across order, payment, fulfillment, and customer records?',unit:'one cancellation or delay event tied to an order version and observation cutoff',scope:'one approved ecommerce cancellation and refund reconciliation lane',sourceBasis:'The FTC rule and business guide describe shipment promises, delay notices, consent, cancellation, and prompt refunds for covered orders. Those U.S. requirements do not automatically govern every merchant or jurisdiction, but they show why timing, consent, shipment, cancellation, and refund are distinct evidence states.',
 population:'Include cancellation requests, delay notices, failed fulfillment, merchant cancellations, payment reversals, refunds, and reopened orders during the window. Stratify by channel, payment method, fulfillment party, shipment state, partial order, refund state, and whether policy or legal review is required.',
 procedure:'Compare request time, promised shipment basis, consent record, warehouse state, carrier evidence, cancellation action, payment action, customer notice, and rendered account status. Preserve conflicts across systems instead of selecting the most convenient status. Route remedy and exception decisions to the authorized merchant owner.',
 measures:'Report requests with complete timing evidence, cross-system state conflicts, shipments after cancellation, cancellation reversals, approved refunds not settled at cutoff, customer-visible mismatches, owner dispositions, and verified final states.',
 boundary:'Support may gather records, apply approved status mappings, flag conflicts, and draft notices. Merchant owners retain legal interpretation, refund approval, partial-remedy decisions, fraud decisions, policy exceptions, and customer commitments outside approved templates.',
 example:'Suppose a customer cancels before the storefront marks an item fulfilled, while the warehouse feed later shows a label created but no carrier acceptance. These are facts from different cutoffs, not proof of shipment or entitlement. Support holds the conflict and assembles the timeline. The merchant owner decides the remedy and communication, after which the reviewer checks payment, order, fulfillment, and customer-visible states.',
 limits:'Carrier latency, split shipments, marketplace rules, payment-network timing, fraud review, digital goods, subscriptions, international law, and customer identity conflicts can change the correct path. The protocol does not determine legal coverage or guarantee settlement timing.',sources:['https://www.ftc.gov/legal-library/browse/rules/mail-internet-or-telephone-order-merchandise-rule','https://www.ftc.gov/business-guidance/resources/selling-internet-prompt-delivery-rules'],sourceRecord:'Mail, Internet, or Telephone Order Merchandise Rule, U.S. Federal Trade Commission, https://www.ftc.gov/legal-library/browse/rules/mail-internet-or-telephone-order-merchandise-rule, checked September 22, 2026. Selling on the Internet: Prompt Delivery Rules, U.S. Federal Trade Commission, https://www.ftc.gov/business-guidance/resources/selling-internet-prompt-delivery-rules, checked September 22, 2026.',related:['philippines-return-refund-operations-research','philippines-ecommerce-customer-care-research'],serviceHandoff:{slug:'ecommerce-operations',label:'Plan ecommerce operations support',text:'Map one cancellation path and keep remedy and legal decisions with the merchant owner.'}
}),
buildArticle({
 slug:'philippines-customer-complaint-disposition-consistency-research',title:'Can complaint disposition records improve customer-support learning?',excerpt:'A customer-experience protocol for issue coding, response evidence, company disposition, and verified closure.',
 statistic:'The U.S. Consumer Financial Protection Bureau says its public Consumer Complaint Database generally updates daily and publishes complaints after the company responds or after 15 days, whichever comes first, with personal information removed.',
 question:'Can customer-support staff record complaint reasons and dispositions consistently without making policy, legal, or remediation decisions?',unit:'one complaint event tied to a controlled customer or case identifier and taxonomy version',scope:'one approved customer complaint disposition workflow',sourceBasis:'CFPB publishes process information, field descriptions, and downloadable complaint data for its own consumer-response system. Its model distinguishes issue, company response, timeliness, consumer dispute, and publication status. A private company should not copy CFPB categories blindly, but the separation illustrates why complaint text, operational coding, company action, and public status are different fields.',
 population:'Include complaints received through approved channels during the window, including duplicates, reopened cases, withdrawn contacts, escalations, and cases awaiting another owner. Stratify by intake channel, issue family, product or service, severity rule, response state, and disposition version.',
 procedure:'Compare the original permitted record with the selected reason code, sub-issue, evidence links, response template, escalation state, owner decision, and final customer-visible outcome. Blind-review a subset against the same taxonomy. Preserve multi-issue cases and uncertainty rather than forcing every record into one convenient category.',
 measures:'Measure taxonomy-version match, supported reason codes, reviewer agreement, multi-issue handling, missing owner decisions, response-state conflicts, reopened cases, changed dispositions, aging at cutoff, and closure verified in the customer-facing system.',
 boundary:'Support may triage, code under approved definitions, collect source links, draft approved responses, and route exceptions. Accountable owners retain policy interpretation, fault findings, compensation, refunds, legal response, regulatory reporting, and sensitive communications.',
 example:'Suppose a customer message describes both delayed delivery and an incorrect charge. The first reviewer selects delivery only because it appears first; the second selects billing because money is involved. The observable disagreement shows that the single-code rule loses information. The support lead records both evidence paths, and the customer-experience owner decides whether to allow multiple codes or define a priority rule. Later review verifies the chosen disposition and actual remedy separately.',
 limits:'Unstructured language, translation, channel loss, duplicate contacts, identity resolution, evolving taxonomies, emotional context, private settlements, and events outside the support system can affect coding. Agreement does not prove that the company response was fair, lawful, or satisfactory.',sources:['https://www.consumerfinance.gov/data-research/consumer-complaints/','https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/'],sourceRecord:'Consumer Complaint Database, Consumer Financial Protection Bureau, https://www.consumerfinance.gov/data-research/consumer-complaints/, checked September 22, 2026. Consumer Complaint Database API documentation, Consumer Financial Protection Bureau, https://www.consumerfinance.gov/data-research/consumer-complaints/search/api/v1/, checked September 22, 2026.',related:['philippines-customer-support-contact-reason-drift-research','philippines-customer-support-qa-sample-stratification-research'],serviceHandoff:{slug:'customer-experience',label:'Plan customer experience support',text:'Start with one complaint taxonomy and a named owner for every remedy and policy decision.'}
})
];
